export const weatherOptions: { value: string; label: string }[] = [
  { value: "sunny", label: "☀️ Sunny" },
  { value: "partly_cloudy", label: "⛅ Partly Cloudy" },
  { value: "cloudy", label: "☁️ Cloudy" },
  { value: "overcast", label: "🌥️ Overcast" },
  { value: "light_rain", label: "🌦️ Light Rain" },
  { value: "rain", label: "🌧️ Rain" },
  { value: "heavy_rain", label: "🌧️ Heavy Rain" },
  { value: "showers", label: "🚿 Showers" },
  { value: "drizzle", label: "💧 Drizzle" },
  { value: "thunderstorm", label: "⛈️ Thunderstorm" },
  { value: "snow", label: "❄️ Snow" },
  { value: "sleet", label: "🌨️ Sleet" },
  { value: "hail", label: "🧊 Hail" },
  { value: "fog", label: "🌫️ Fog" },
  { value: "mist", label: "🌁 Mist" },
  { value: "windy", label: "💨 Windy" },
  { value: "clear", label: "🌙 Clear" },
  { value: "frost", label: "🥶 Frost" },
  { value: "hot", label: "🔥 Hot" },
  { value: "cold", label: "🥶 Cold" },
]
