// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createClient, createFile, createFiles, createJob, createProject, createRun, deleteClient, deleteJob, deleteProject, generateFileDownloadUrl, generateFileUploadUrls, loginUser, logoutUser, type Options, readClient, readClients, readFile, readFiles, readJob, readJobs, readProject, readProjects, readProjectTypes, readRun, readRunArtefacts, readRuns, readUserMe, registerUser, updateClient, updateJob, updateProject, updateUserMe } from '../sdk.gen';
import type { CreateClientData, CreateClientError, CreateClientResponse, CreateFileData, CreateFileError, CreateFileResponse, CreateFilesData, CreateFilesError, CreateFilesResponse, CreateJobData, CreateJobError, CreateJobResponse, CreateProjectData, CreateProjectError, CreateProjectResponse, CreateRunData, CreateRunError, CreateRunResponse, DeleteClientData, DeleteClientError, DeleteClientResponse, DeleteJobData, DeleteJobError, DeleteJobResponse, DeleteProjectData, DeleteProjectError, DeleteProjectResponse, GenerateFileDownloadUrlData, GenerateFileDownloadUrlError, GenerateFileDownloadUrlResponse, GenerateFileUploadUrlsData, GenerateFileUploadUrlsError, GenerateFileUploadUrlsResponse, LoginUserData, LoginUserError, LogoutUserData, LogoutUserError, ReadClientData, ReadClientError, ReadClientResponse, ReadClientsData, ReadClientsError, ReadClientsResponse, ReadFileData, ReadFileError, ReadFileResponse, ReadFilesData, ReadFilesError, ReadFilesResponse, ReadJobData, ReadJobError, ReadJobResponse, ReadJobsData, ReadJobsError, ReadJobsResponse, ReadProjectData, ReadProjectError, ReadProjectResponse, ReadProjectsData, ReadProjectsError, ReadProjectsResponse, ReadProjectTypesData, ReadProjectTypesResponse, ReadRunArtefactsData, ReadRunArtefactsError, ReadRunArtefactsResponse, ReadRunData, ReadRunError, ReadRunResponse, ReadRunsData, ReadRunsError, ReadRunsResponse, ReadUserMeData, ReadUserMeResponse, RegisterUserData, RegisterUserError, RegisterUserResponse, UpdateClientData, UpdateClientError, UpdateClientResponse, UpdateJobData, UpdateJobError, UpdateJobResponse, UpdateProjectData, UpdateProjectError, UpdateProjectResponse, UpdateUserMeData, UpdateUserMeError, UpdateUserMeResponse } from '../types.gen';

/**
 * Login
 */
export const loginUserMutation = (options?: Partial<Options<LoginUserData>>): UseMutationOptions<unknown, LoginUserError, Options<LoginUserData>> => {
    const mutationOptions: UseMutationOptions<unknown, LoginUserError, Options<LoginUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 */
export const logoutUserMutation = (options?: Partial<Options<LogoutUserData>>): UseMutationOptions<unknown, LogoutUserError, Options<LogoutUserData>> => {
    const mutationOptions: UseMutationOptions<unknown, LogoutUserError, Options<LogoutUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logoutUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const readRunsQueryKey = (options?: Options<ReadRunsData>) => createQueryKey('readRuns', options);

/**
 * Read Runs
 *
 * Retrieve document generation runs for the current user's organization.
 */
export const readRunsOptions = (options?: Options<ReadRunsData>) => queryOptions<ReadRunsResponse, ReadRunsError, ReadRunsResponse, ReturnType<typeof readRunsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readRuns({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readRunsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const readRunsInfiniteQueryKey = (options?: Options<ReadRunsData>): QueryKey<Options<ReadRunsData>> => createQueryKey('readRuns', options, true);

/**
 * Read Runs
 *
 * Retrieve document generation runs for the current user's organization.
 */
export const readRunsInfiniteOptions = (options?: Options<ReadRunsData>) => infiniteQueryOptions<ReadRunsResponse, ReadRunsError, InfiniteData<ReadRunsResponse>, QueryKey<Options<ReadRunsData>>, number | Pick<QueryKey<Options<ReadRunsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ReadRunsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await readRuns({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readRunsInfiniteQueryKey(options)
});

/**
 * Create Run
 *
 * Create a new document generation run and start the orchestrator in the background.
 */
export const createRunMutation = (options?: Partial<Options<CreateRunData>>): UseMutationOptions<CreateRunResponse, CreateRunError, Options<CreateRunData>> => {
    const mutationOptions: UseMutationOptions<CreateRunResponse, CreateRunError, Options<CreateRunData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createRun({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readRunQueryKey = (options: Options<ReadRunData>) => createQueryKey('readRun', options);

/**
 * Read Run
 *
 * Retrieve a document generation run by its ID.
 */
export const readRunOptions = (options: Options<ReadRunData>) => queryOptions<ReadRunResponse, ReadRunError, ReadRunResponse, ReturnType<typeof readRunQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readRun({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readRunQueryKey(options)
});

export const readRunArtefactsQueryKey = (options: Options<ReadRunArtefactsData>) => createQueryKey('readRunArtefacts', options);

/**
 * Read Run Artefacts
 *
 * Retrieve artefacts for a run.
 */
export const readRunArtefactsOptions = (options: Options<ReadRunArtefactsData>) => queryOptions<ReadRunArtefactsResponse, ReadRunArtefactsError, ReadRunArtefactsResponse, ReturnType<typeof readRunArtefactsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readRunArtefacts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readRunArtefactsQueryKey(options)
});

/**
 * Generate Upload Urls
 *
 * Generate presigned PUT URLs. Does NOT create DB records yet.
 */
export const generateFileUploadUrlsMutation = (options?: Partial<Options<GenerateFileUploadUrlsData>>): UseMutationOptions<GenerateFileUploadUrlsResponse, GenerateFileUploadUrlsError, Options<GenerateFileUploadUrlsData>> => {
    const mutationOptions: UseMutationOptions<GenerateFileUploadUrlsResponse, GenerateFileUploadUrlsError, Options<GenerateFileUploadUrlsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await generateFileUploadUrls({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create File
 *
 * Standard Create Endpoint.
 * Client calls this AFTER successfully uploading to the presigned URL.
 */
export const createFileMutation = (options?: Partial<Options<CreateFileData>>): UseMutationOptions<CreateFileResponse, CreateFileError, Options<CreateFileData>> => {
    const mutationOptions: UseMutationOptions<CreateFileResponse, CreateFileError, Options<CreateFileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createFile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readFilesQueryKey = (options?: Options<ReadFilesData>) => createQueryKey('readFiles', options);

/**
 * Read Files
 *
 * Retrieve files.
 */
export const readFilesOptions = (options?: Options<ReadFilesData>) => queryOptions<ReadFilesResponse, ReadFilesError, ReadFilesResponse, ReturnType<typeof readFilesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readFiles({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readFilesQueryKey(options)
});

export const readFilesInfiniteQueryKey = (options?: Options<ReadFilesData>): QueryKey<Options<ReadFilesData>> => createQueryKey('readFiles', options, true);

/**
 * Read Files
 *
 * Retrieve files.
 */
export const readFilesInfiniteOptions = (options?: Options<ReadFilesData>) => infiniteQueryOptions<ReadFilesResponse, ReadFilesError, InfiniteData<ReadFilesResponse>, QueryKey<Options<ReadFilesData>>, number | Pick<QueryKey<Options<ReadFilesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ReadFilesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await readFiles({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readFilesInfiniteQueryKey(options)
});

/**
 * Create Files
 *
 * Create Endpoint for multiple files.
 */
export const createFilesMutation = (options?: Partial<Options<CreateFilesData>>): UseMutationOptions<CreateFilesResponse, CreateFilesError, Options<CreateFilesData>> => {
    const mutationOptions: UseMutationOptions<CreateFilesResponse, CreateFilesError, Options<CreateFilesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createFiles({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readFileQueryKey = (options: Options<ReadFileData>) => createQueryKey('readFile', options);

/**
 * Read File
 *
 * Get file metadata by ID.
 */
export const readFileOptions = (options: Options<ReadFileData>) => queryOptions<ReadFileResponse, ReadFileError, ReadFileResponse, ReturnType<typeof readFileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readFile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readFileQueryKey(options)
});

export const generateFileDownloadUrlQueryKey = (options: Options<GenerateFileDownloadUrlData>) => createQueryKey('generateFileDownloadUrl', options);

/**
 * Generate Download Url
 *
 * Generate a presigned download URL for a file.
 *
 * Args:
 * inline: If True, sets content-disposition to inline (for browser preview).
 * If False (default), sets to attachment (for download).
 */
export const generateFileDownloadUrlOptions = (options: Options<GenerateFileDownloadUrlData>) => queryOptions<GenerateFileDownloadUrlResponse, GenerateFileDownloadUrlError, GenerateFileDownloadUrlResponse, ReturnType<typeof generateFileDownloadUrlQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await generateFileDownloadUrl({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: generateFileDownloadUrlQueryKey(options)
});

export const readJobsQueryKey = (options?: Options<ReadJobsData>) => createQueryKey('readJobs', options);

/**
 * Read Jobs
 */
export const readJobsOptions = (options?: Options<ReadJobsData>) => queryOptions<ReadJobsResponse, ReadJobsError, ReadJobsResponse, ReturnType<typeof readJobsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readJobs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readJobsQueryKey(options)
});

/**
 * Create Job
 */
export const createJobMutation = (options?: Partial<Options<CreateJobData>>): UseMutationOptions<CreateJobResponse, CreateJobError, Options<CreateJobData>> => {
    const mutationOptions: UseMutationOptions<CreateJobResponse, CreateJobError, Options<CreateJobData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createJob({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Job
 */
export const deleteJobMutation = (options?: Partial<Options<DeleteJobData>>): UseMutationOptions<DeleteJobResponse, DeleteJobError, Options<DeleteJobData>> => {
    const mutationOptions: UseMutationOptions<DeleteJobResponse, DeleteJobError, Options<DeleteJobData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteJob({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readJobQueryKey = (options: Options<ReadJobData>) => createQueryKey('readJob', options);

/**
 * Read Job
 */
export const readJobOptions = (options: Options<ReadJobData>) => queryOptions<ReadJobResponse, ReadJobError, ReadJobResponse, ReturnType<typeof readJobQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readJob({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readJobQueryKey(options)
});

/**
 * Update Job
 */
export const updateJobMutation = (options?: Partial<Options<UpdateJobData>>): UseMutationOptions<UpdateJobResponse, UpdateJobError, Options<UpdateJobData>> => {
    const mutationOptions: UseMutationOptions<UpdateJobResponse, UpdateJobError, Options<UpdateJobData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateJob({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readProjectTypesQueryKey = (options?: Options<ReadProjectTypesData>) => createQueryKey('readProjectTypes', options);

/**
 * Read Project Types
 */
export const readProjectTypesOptions = (options?: Options<ReadProjectTypesData>) => queryOptions<ReadProjectTypesResponse, DefaultError, ReadProjectTypesResponse, ReturnType<typeof readProjectTypesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readProjectTypes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readProjectTypesQueryKey(options)
});

export const readProjectsQueryKey = (options?: Options<ReadProjectsData>) => createQueryKey('readProjects', options);

/**
 * Read Projects
 */
export const readProjectsOptions = (options?: Options<ReadProjectsData>) => queryOptions<ReadProjectsResponse, ReadProjectsError, ReadProjectsResponse, ReturnType<typeof readProjectsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readProjects({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readProjectsQueryKey(options)
});

export const readProjectsInfiniteQueryKey = (options?: Options<ReadProjectsData>): QueryKey<Options<ReadProjectsData>> => createQueryKey('readProjects', options, true);

/**
 * Read Projects
 */
export const readProjectsInfiniteOptions = (options?: Options<ReadProjectsData>) => infiniteQueryOptions<ReadProjectsResponse, ReadProjectsError, InfiniteData<ReadProjectsResponse>, QueryKey<Options<ReadProjectsData>>, number | Pick<QueryKey<Options<ReadProjectsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ReadProjectsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await readProjects({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readProjectsInfiniteQueryKey(options)
});

/**
 * Create Project
 */
export const createProjectMutation = (options?: Partial<Options<CreateProjectData>>): UseMutationOptions<CreateProjectResponse, CreateProjectError, Options<CreateProjectData>> => {
    const mutationOptions: UseMutationOptions<CreateProjectResponse, CreateProjectError, Options<CreateProjectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createProject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Project
 */
export const deleteProjectMutation = (options?: Partial<Options<DeleteProjectData>>): UseMutationOptions<DeleteProjectResponse, DeleteProjectError, Options<DeleteProjectData>> => {
    const mutationOptions: UseMutationOptions<DeleteProjectResponse, DeleteProjectError, Options<DeleteProjectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteProject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readProjectQueryKey = (options: Options<ReadProjectData>) => createQueryKey('readProject', options);

/**
 * Read Project
 */
export const readProjectOptions = (options: Options<ReadProjectData>) => queryOptions<ReadProjectResponse, ReadProjectError, ReadProjectResponse, ReturnType<typeof readProjectQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readProject({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readProjectQueryKey(options)
});

/**
 * Update Project
 */
export const updateProjectMutation = (options?: Partial<Options<UpdateProjectData>>): UseMutationOptions<UpdateProjectResponse, UpdateProjectError, Options<UpdateProjectData>> => {
    const mutationOptions: UseMutationOptions<UpdateProjectResponse, UpdateProjectError, Options<UpdateProjectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateProject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register User
 *
 * Register a new user.
 */
export const registerUserMutation = (options?: Partial<Options<RegisterUserData>>): UseMutationOptions<RegisterUserResponse, RegisterUserError, Options<RegisterUserData>> => {
    const mutationOptions: UseMutationOptions<RegisterUserResponse, RegisterUserError, Options<RegisterUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await registerUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readUserMeQueryKey = (options?: Options<ReadUserMeData>) => createQueryKey('readUserMe', options);

/**
 * Read User Me
 *
 * Get current user.
 */
export const readUserMeOptions = (options?: Options<ReadUserMeData>) => queryOptions<ReadUserMeResponse, DefaultError, ReadUserMeResponse, ReturnType<typeof readUserMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readUserMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readUserMeQueryKey(options)
});

/**
 * Update User Me
 *
 * Update own profile.
 */
export const updateUserMeMutation = (options?: Partial<Options<UpdateUserMeData>>): UseMutationOptions<UpdateUserMeResponse, UpdateUserMeError, Options<UpdateUserMeData>> => {
    const mutationOptions: UseMutationOptions<UpdateUserMeResponse, UpdateUserMeError, Options<UpdateUserMeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateUserMe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readClientsQueryKey = (options?: Options<ReadClientsData>) => createQueryKey('readClients', options);

/**
 * Read Clients
 *
 * Retrieve clients.
 */
export const readClientsOptions = (options?: Options<ReadClientsData>) => queryOptions<ReadClientsResponse, ReadClientsError, ReadClientsResponse, ReturnType<typeof readClientsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readClients({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readClientsQueryKey(options)
});

export const readClientsInfiniteQueryKey = (options?: Options<ReadClientsData>): QueryKey<Options<ReadClientsData>> => createQueryKey('readClients', options, true);

/**
 * Read Clients
 *
 * Retrieve clients.
 */
export const readClientsInfiniteOptions = (options?: Options<ReadClientsData>) => infiniteQueryOptions<ReadClientsResponse, ReadClientsError, InfiniteData<ReadClientsResponse>, QueryKey<Options<ReadClientsData>>, number | Pick<QueryKey<Options<ReadClientsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ReadClientsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await readClients({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readClientsInfiniteQueryKey(options)
});

/**
 * Create Client
 *
 * Create a new client.
 */
export const createClientMutation = (options?: Partial<Options<CreateClientData>>): UseMutationOptions<CreateClientResponse, CreateClientError, Options<CreateClientData>> => {
    const mutationOptions: UseMutationOptions<CreateClientResponse, CreateClientError, Options<CreateClientData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createClient({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Client
 */
export const deleteClientMutation = (options?: Partial<Options<DeleteClientData>>): UseMutationOptions<DeleteClientResponse, DeleteClientError, Options<DeleteClientData>> => {
    const mutationOptions: UseMutationOptions<DeleteClientResponse, DeleteClientError, Options<DeleteClientData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteClient({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const readClientQueryKey = (options: Options<ReadClientData>) => createQueryKey('readClient', options);

/**
 * Read Client
 */
export const readClientOptions = (options: Options<ReadClientData>) => queryOptions<ReadClientResponse, ReadClientError, ReadClientResponse, ReturnType<typeof readClientQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readClient({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readClientQueryKey(options)
});

/**
 * Update Client
 */
export const updateClientMutation = (options?: Partial<Options<UpdateClientData>>): UseMutationOptions<UpdateClientResponse, UpdateClientError, Options<UpdateClientData>> => {
    const mutationOptions: UseMutationOptions<UpdateClientResponse, UpdateClientError, Options<UpdateClientData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateClient({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
