// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateClientData, CreateClientErrors, CreateClientResponses, CreateFileData, CreateFileErrors, CreateFileResponses, CreateFilesData, CreateFilesErrors, CreateFilesResponses, CreateJobData, CreateJobErrors, CreateJobResponses, CreateProjectData, CreateProjectErrors, CreateProjectResponses, CreateRunData, CreateRunErrors, CreateRunResponses, DeleteClientData, DeleteClientErrors, DeleteClientResponses, DeleteJobData, DeleteJobErrors, DeleteJobResponses, DeleteProjectData, DeleteProjectErrors, DeleteProjectResponses, GenerateFileDownloadUrlData, GenerateFileDownloadUrlErrors, GenerateFileDownloadUrlResponses, GenerateFileUploadUrlsData, GenerateFileUploadUrlsErrors, GenerateFileUploadUrlsResponses, LoginUserData, LoginUserErrors, LoginUserResponses, LogoutUserData, LogoutUserErrors, LogoutUserResponses, ReadClientData, ReadClientErrors, ReadClientResponses, ReadClientsData, ReadClientsErrors, ReadClientsResponses, ReadFileData, ReadFileErrors, ReadFileResponses, ReadFilesData, ReadFilesErrors, ReadFilesResponses, ReadJobData, ReadJobErrors, ReadJobResponses, ReadJobsData, ReadJobsErrors, ReadJobsResponses, ReadProjectData, ReadProjectErrors, ReadProjectResponses, ReadProjectsData, ReadProjectsErrors, ReadProjectsResponses, ReadProjectTypesData, ReadProjectTypesResponses, ReadRunArtefactsData, ReadRunArtefactsErrors, ReadRunArtefactsResponses, ReadRunData, ReadRunErrors, ReadRunResponses, ReadRunsData, ReadRunsErrors, ReadRunsResponses, ReadUserMeData, ReadUserMeResponses, RegisterUserData, RegisterUserErrors, RegisterUserResponses, UpdateClientData, UpdateClientErrors, UpdateClientResponses, UpdateJobData, UpdateJobErrors, UpdateJobResponses, UpdateProjectData, UpdateProjectErrors, UpdateProjectResponses, UpdateUserMeData, UpdateUserMeErrors, UpdateUserMeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 */
export const loginUser = <ThrowOnError extends boolean = false>(options: Options<LoginUserData, ThrowOnError>) => (options.client ?? client).post<LoginUserResponses, LoginUserErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 */
export const logoutUser = <ThrowOnError extends boolean = false>(options?: Options<LogoutUserData, ThrowOnError>) => (options?.client ?? client).post<LogoutUserResponses, LogoutUserErrors, ThrowOnError>({ url: '/auth/logout', ...options });

/**
 * Read Runs
 *
 * Retrieve document generation runs for the current user's organization.
 */
export const readRuns = <ThrowOnError extends boolean = false>(options?: Options<ReadRunsData, ThrowOnError>) => (options?.client ?? client).get<ReadRunsResponses, ReadRunsErrors, ThrowOnError>({ url: '/runs/', ...options });

/**
 * Create Run
 *
 * Create a new document generation run and start the orchestrator in the background.
 */
export const createRun = <ThrowOnError extends boolean = false>(options: Options<CreateRunData, ThrowOnError>) => (options.client ?? client).post<CreateRunResponses, CreateRunErrors, ThrowOnError>({
    url: '/runs/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Run
 *
 * Retrieve a document generation run by its ID.
 */
export const readRun = <ThrowOnError extends boolean = false>(options: Options<ReadRunData, ThrowOnError>) => (options.client ?? client).get<ReadRunResponses, ReadRunErrors, ThrowOnError>({ url: '/runs/{run_id}', ...options });

/**
 * Read Run Artefacts
 *
 * Retrieve artefacts for a run.
 */
export const readRunArtefacts = <ThrowOnError extends boolean = false>(options: Options<ReadRunArtefactsData, ThrowOnError>) => (options.client ?? client).get<ReadRunArtefactsResponses, ReadRunArtefactsErrors, ThrowOnError>({ url: '/runs/{run_id}/artefacts', ...options });

/**
 * Generate Upload Urls
 *
 * Generate presigned PUT URLs. Does NOT create DB records yet.
 */
export const generateFileUploadUrls = <ThrowOnError extends boolean = false>(options: Options<GenerateFileUploadUrlsData, ThrowOnError>) => (options.client ?? client).post<GenerateFileUploadUrlsResponses, GenerateFileUploadUrlsErrors, ThrowOnError>({
    url: '/store/presign',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create File
 *
 * Standard Create Endpoint.
 * Client calls this AFTER successfully uploading to the presigned URL.
 */
export const createFile = <ThrowOnError extends boolean = false>(options: Options<CreateFileData, ThrowOnError>) => (options.client ?? client).post<CreateFileResponses, CreateFileErrors, ThrowOnError>({
    url: '/store/single',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Files
 *
 * Retrieve files.
 */
export const readFiles = <ThrowOnError extends boolean = false>(options?: Options<ReadFilesData, ThrowOnError>) => (options?.client ?? client).get<ReadFilesResponses, ReadFilesErrors, ThrowOnError>({ url: '/store/', ...options });

/**
 * Create Files
 *
 * Create Endpoint for multiple files.
 */
export const createFiles = <ThrowOnError extends boolean = false>(options: Options<CreateFilesData, ThrowOnError>) => (options.client ?? client).post<CreateFilesResponses, CreateFilesErrors, ThrowOnError>({
    url: '/store/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read File
 *
 * Get file metadata by ID.
 */
export const readFile = <ThrowOnError extends boolean = false>(options: Options<ReadFileData, ThrowOnError>) => (options.client ?? client).get<ReadFileResponses, ReadFileErrors, ThrowOnError>({ url: '/store/{file_id}', ...options });

/**
 * Generate Download Url
 *
 * Generate a presigned download URL for a file.
 *
 * Args:
 * inline: If True, sets content-disposition to inline (for browser preview).
 * If False (default), sets to attachment (for download).
 */
export const generateFileDownloadUrl = <ThrowOnError extends boolean = false>(options: Options<GenerateFileDownloadUrlData, ThrowOnError>) => (options.client ?? client).get<GenerateFileDownloadUrlResponses, GenerateFileDownloadUrlErrors, ThrowOnError>({ url: '/store/{file_id}/download', ...options });

/**
 * Read Jobs
 */
export const readJobs = <ThrowOnError extends boolean = false>(options?: Options<ReadJobsData, ThrowOnError>) => (options?.client ?? client).get<ReadJobsResponses, ReadJobsErrors, ThrowOnError>({ url: '/jobs/', ...options });

/**
 * Create Job
 */
export const createJob = <ThrowOnError extends boolean = false>(options: Options<CreateJobData, ThrowOnError>) => (options.client ?? client).post<CreateJobResponses, CreateJobErrors, ThrowOnError>({
    url: '/jobs/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Job
 */
export const deleteJob = <ThrowOnError extends boolean = false>(options: Options<DeleteJobData, ThrowOnError>) => (options.client ?? client).delete<DeleteJobResponses, DeleteJobErrors, ThrowOnError>({ url: '/jobs/{job_id}', ...options });

/**
 * Read Job
 */
export const readJob = <ThrowOnError extends boolean = false>(options: Options<ReadJobData, ThrowOnError>) => (options.client ?? client).get<ReadJobResponses, ReadJobErrors, ThrowOnError>({ url: '/jobs/{job_id}', ...options });

/**
 * Update Job
 */
export const updateJob = <ThrowOnError extends boolean = false>(options: Options<UpdateJobData, ThrowOnError>) => (options.client ?? client).patch<UpdateJobResponses, UpdateJobErrors, ThrowOnError>({
    url: '/jobs/{job_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Project Types
 */
export const readProjectTypes = <ThrowOnError extends boolean = false>(options?: Options<ReadProjectTypesData, ThrowOnError>) => (options?.client ?? client).get<ReadProjectTypesResponses, unknown, ThrowOnError>({ url: '/projects/types', ...options });

/**
 * Read Projects
 */
export const readProjects = <ThrowOnError extends boolean = false>(options?: Options<ReadProjectsData, ThrowOnError>) => (options?.client ?? client).get<ReadProjectsResponses, ReadProjectsErrors, ThrowOnError>({ url: '/projects/', ...options });

/**
 * Create Project
 */
export const createProject = <ThrowOnError extends boolean = false>(options: Options<CreateProjectData, ThrowOnError>) => (options.client ?? client).post<CreateProjectResponses, CreateProjectErrors, ThrowOnError>({
    url: '/projects/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Project
 */
export const deleteProject = <ThrowOnError extends boolean = false>(options: Options<DeleteProjectData, ThrowOnError>) => (options.client ?? client).delete<DeleteProjectResponses, DeleteProjectErrors, ThrowOnError>({ url: '/projects/{project_id}', ...options });

/**
 * Read Project
 */
export const readProject = <ThrowOnError extends boolean = false>(options: Options<ReadProjectData, ThrowOnError>) => (options.client ?? client).get<ReadProjectResponses, ReadProjectErrors, ThrowOnError>({ url: '/projects/{project_id}', ...options });

/**
 * Update Project
 */
export const updateProject = <ThrowOnError extends boolean = false>(options: Options<UpdateProjectData, ThrowOnError>) => (options.client ?? client).patch<UpdateProjectResponses, UpdateProjectErrors, ThrowOnError>({
    url: '/projects/{project_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register User
 *
 * Register a new user.
 */
export const registerUser = <ThrowOnError extends boolean = false>(options: Options<RegisterUserData, ThrowOnError>) => (options.client ?? client).post<RegisterUserResponses, RegisterUserErrors, ThrowOnError>({
    url: '/users/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read User Me
 *
 * Get current user.
 */
export const readUserMe = <ThrowOnError extends boolean = false>(options?: Options<ReadUserMeData, ThrowOnError>) => (options?.client ?? client).get<ReadUserMeResponses, unknown, ThrowOnError>({ url: '/users/me', ...options });

/**
 * Update User Me
 *
 * Update own profile.
 */
export const updateUserMe = <ThrowOnError extends boolean = false>(options: Options<UpdateUserMeData, ThrowOnError>) => (options.client ?? client).patch<UpdateUserMeResponses, UpdateUserMeErrors, ThrowOnError>({
    url: '/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Clients
 *
 * Retrieve clients.
 */
export const readClients = <ThrowOnError extends boolean = false>(options?: Options<ReadClientsData, ThrowOnError>) => (options?.client ?? client).get<ReadClientsResponses, ReadClientsErrors, ThrowOnError>({ url: '/clients/', ...options });

/**
 * Create Client
 *
 * Create a new client.
 */
export const createClient = <ThrowOnError extends boolean = false>(options: Options<CreateClientData, ThrowOnError>) => (options.client ?? client).post<CreateClientResponses, CreateClientErrors, ThrowOnError>({
    url: '/clients/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Client
 */
export const deleteClient = <ThrowOnError extends boolean = false>(options: Options<DeleteClientData, ThrowOnError>) => (options.client ?? client).delete<DeleteClientResponses, DeleteClientErrors, ThrowOnError>({ url: '/clients/{client_id}', ...options });

/**
 * Read Client
 */
export const readClient = <ThrowOnError extends boolean = false>(options: Options<ReadClientData, ThrowOnError>) => (options.client ?? client).get<ReadClientResponses, ReadClientErrors, ThrowOnError>({ url: '/clients/{client_id}', ...options });

/**
 * Update Client
 */
export const updateClient = <ThrowOnError extends boolean = false>(options: Options<UpdateClientData, ThrowOnError>) => (options.client ?? client).patch<UpdateClientResponses, UpdateClientErrors, ThrowOnError>({
    url: '/clients/{client_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
