// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Artefact
 */
export type Artefact = {
    artefact_type: ArtefactType;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Version
     */
    version: number;
    /**
     * Id
     */
    id?: number | null;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Org Id
     */
    org_id?: number;
    /**
     * Job Id
     */
    job_id?: number | null;
    /**
     * Run Id
     */
    run_id: number;
    /**
     * File Id
     */
    file_id: number;
    /**
     * Preview File Id
     */
    preview_file_id?: number | null;
};

/**
 * ArtefactType
 */
export const ArtefactType = { '.DOCX': '.docx', '.XLSX': '.xlsx' } as const;

/**
 * ArtefactType
 */
export type ArtefactType = typeof ArtefactType[keyof typeof ArtefactType];

/**
 * ClientContactCreate
 */
export type ClientContactCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Role Title
     */
    role_title?: string | null;
};

/**
 * ClientContactRead
 */
export type ClientContactRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Role Title
     */
    role_title?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Client Id
     */
    client_id: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ClientCreate
 */
export type ClientCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Contacts
     */
    contacts?: Array<ClientContactCreate>;
};

/**
 * ClientRead
 */
export type ClientRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Org Id
     */
    org_id: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Contacts
     */
    contacts?: Array<ClientContactRead>;
};

/**
 * ClientReadDetail
 */
export type ClientReadDetail = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Org Id
     */
    org_id: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Contacts
     */
    contacts?: Array<ClientContactRead>;
    /**
     * Jobs
     */
    jobs: Array<JobReadMinimal>;
};

/**
 * ClientReadMinimal
 */
export type ClientReadMinimal = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Id
     */
    id: number;
};

/**
 * ClientUpdate
 */
export type ClientUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Address
     */
    address?: string | null;
};

/**
 * ConvertLeadResponse
 */
export type ConvertLeadResponse = {
    /**
     * Client Id
     */
    client_id: number;
    /**
     * Contact Id
     */
    contact_id?: number | null;
};

/**
 * ConvertQuoteResponse
 */
export type ConvertQuoteResponse = {
    /**
     * Job Id
     */
    job_id: number;
    /**
     * Client Id
     */
    client_id?: number | null;
};

/**
 * FeeType
 */
export const FeeType = {
    FIXED: 'fixed',
    HOURLY: 'hourly',
    MIXED: 'mixed'
} as const;

/**
 * FeeType
 */
export type FeeType = typeof FeeType[keyof typeof FeeType];

/**
 * FileCreate
 */
export type FileCreate = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Size Bytes
     */
    size_bytes?: number | null;
    /**
     * Storage Key
     */
    storage_key: string;
    /**
     * Org Id
     */
    org_id: number;
    /**
     * Uploaded By User Id
     */
    uploaded_by_user_id?: number | null;
    /**
     * Job Id
     */
    job_id?: number | null;
    /**
     * Run Id
     */
    run_id?: number | null;
    role?: FileRole;
};

/**
 * FilePresignRequest
 */
export type FilePresignRequest = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Size Bytes
     */
    size_bytes?: number | null;
    /**
     * Client Id
     */
    client_id: string;
};

/**
 * FilePresignResponse
 */
export type FilePresignResponse = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Size Bytes
     */
    size_bytes?: number | null;
    /**
     * Client Id
     */
    client_id: string;
    /**
     * Put Url
     */
    put_url: string;
    /**
     * Storage Key
     */
    storage_key: string;
};

/**
 * FileRead
 */
export type FileRead = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Size Bytes
     */
    size_bytes?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Storage Key
     */
    storage_key: string;
    /**
     * Uploaded By User Id
     */
    uploaded_by_user_id: number;
    /**
     * Created At
     */
    created_at: string;
    role: FileRole;
};

/**
 * FileRole
 */
export const FileRole = {
    TEMPLATE: 'template',
    PREVIEW_PDF: 'preview_pdf',
    ARTEFACT: 'artefact',
    INPUT: 'input'
} as const;

/**
 * FileRole
 */
export type FileRole = typeof FileRole[keyof typeof FileRole];

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobCreate
 */
export type JobCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    status?: JobStatus | null;
    /**
     * Updates
     */
    updates?: Array<unknown> | null;
    /**
     * Client Id
     */
    client_id: number;
    /**
     * Lead User Id
     */
    lead_user_id?: number | null;
};

/**
 * JobRead
 */
export type JobRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    status?: JobStatus | null;
    /**
     * Updates
     */
    updates?: Array<unknown> | null;
    /**
     * Id
     */
    id: number;
    client: ClientReadMinimal;
    created_by_user: UserRead;
    lead_user: UserRead | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * JobReadDetail
 */
export type JobReadDetail = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    status?: JobStatus | null;
    /**
     * Updates
     */
    updates?: Array<unknown> | null;
    /**
     * Id
     */
    id: number;
    client: ClientReadMinimal;
    created_by_user: UserRead;
    lead_user: UserRead | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Projects
     */
    projects: Array<ProjectRead>;
    /**
     * Files
     */
    files: Array<FileRead>;
};

/**
 * JobReadMinimal
 */
export type JobReadMinimal = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    status?: JobStatus | null;
    /**
     * Updates
     */
    updates?: Array<unknown> | null;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * JobStatus
 */
export const JobStatus = {
    PLANNED: 'planned',
    ACTIVE: 'active',
    COMPLETED: 'completed',
    ARCHIVED: 'archived'
} as const;

/**
 * JobStatus
 */
export type JobStatus = typeof JobStatus[keyof typeof JobStatus];

/**
 * JobUpdate
 */
export type JobUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Address
     */
    address?: string | null;
    status?: JobStatus | null;
    /**
     * Client Id
     */
    client_id?: number | null;
    /**
     * Lead User Id
     */
    lead_user_id?: number | null;
    /**
     * Updates
     */
    updates?: Array<unknown> | null;
};

/**
 * JobUpdateEntry
 */
export type JobUpdateEntry = {
    /**
     * Text
     */
    text: string;
};

/**
 * LeadCreate
 */
export type LeadCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Contact Name
     */
    contact_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    status?: LeadStatus;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * LeadRead
 */
export type LeadRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Contact Name
     */
    contact_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    status?: LeadStatus;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Org Id
     */
    org_id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Updates
     */
    updates?: Array<unknown> | null;
    /**
     * Converted Client Id
     */
    converted_client_id?: number | null;
};

/**
 * LeadReadMinimal
 */
export type LeadReadMinimal = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Contact Name
     */
    contact_name?: string | null;
    status: LeadStatus;
};

/**
 * LeadStatus
 */
export const LeadStatus = {
    NEW: 'new',
    CONTACTED: 'contacted',
    QUOTED: 'quoted',
    CONVERTED: 'converted',
    LOST: 'lost'
} as const;

/**
 * LeadStatus
 */
export type LeadStatus = typeof LeadStatus[keyof typeof LeadStatus];

/**
 * LeadUpdate
 */
export type LeadUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Contact Name
     */
    contact_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    status?: LeadStatus | null;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * LeadUpdateEntry
 */
export type LeadUpdateEntry = {
    /**
     * Text
     */
    text: string;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Rate
     */
    rate?: number | null;
    /**
     * Forecasted Billable Hours
     */
    forecasted_billable_hours?: number | null;
    /**
     * Actual Hours
     */
    actual_hours?: number | null;
    /**
     * Contingency Percentage
     */
    contingency_percentage?: number | null;
    /**
     * Forecasted Settlement Amount
     */
    forecasted_settlement_amount?: number | null;
    /**
     * Final Settlement Amount
     */
    final_settlement_amount?: number | null;
    /**
     * Forecasted Fee Amount
     */
    forecasted_fee_amount?: number | null;
    fee_type: FeeType;
    status?: ProjectStatus | null;
    /**
     * Updates
     */
    updates?: Array<string> | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Deadline
     */
    deadline?: string | null;
    /**
     * Lead User Id
     */
    lead_user_id?: number | null;
    /**
     * Job Id
     */
    job_id: number;
    /**
     * Project Type Id
     */
    project_type_id?: number | null;
};

/**
 * ProjectRead
 */
export type ProjectRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Rate
     */
    rate?: number | null;
    /**
     * Forecasted Billable Hours
     */
    forecasted_billable_hours?: number | null;
    /**
     * Actual Hours
     */
    actual_hours?: number | null;
    /**
     * Contingency Percentage
     */
    contingency_percentage?: number | null;
    /**
     * Forecasted Settlement Amount
     */
    forecasted_settlement_amount?: number | null;
    /**
     * Final Settlement Amount
     */
    final_settlement_amount?: number | null;
    /**
     * Forecasted Fee Amount
     */
    forecasted_fee_amount?: number | null;
    fee_type: FeeType;
    status?: ProjectStatus | null;
    /**
     * Updates
     */
    updates?: Array<string> | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Deadline
     */
    deadline?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Project Type Id
     */
    project_type_id: number;
    /**
     * Job Id
     */
    job_id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProjectReadDetail
 */
export type ProjectReadDetail = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Rate
     */
    rate?: number | null;
    /**
     * Forecasted Billable Hours
     */
    forecasted_billable_hours?: number | null;
    /**
     * Actual Hours
     */
    actual_hours?: number | null;
    /**
     * Contingency Percentage
     */
    contingency_percentage?: number | null;
    /**
     * Forecasted Settlement Amount
     */
    forecasted_settlement_amount?: number | null;
    /**
     * Final Settlement Amount
     */
    final_settlement_amount?: number | null;
    /**
     * Forecasted Fee Amount
     */
    forecasted_fee_amount?: number | null;
    fee_type: FeeType;
    status?: ProjectStatus | null;
    /**
     * Updates
     */
    updates?: Array<string> | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Deadline
     */
    deadline?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Project Type Id
     */
    project_type_id: number;
    /**
     * Job Id
     */
    job_id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    project_type: ProjectTypeRead;
    job: JobReadMinimal;
};

/**
 * ProjectStatus
 */
export const ProjectStatus = {
    PLANNED: 'planned',
    ACTIVE: 'active',
    COMPLETED: 'completed',
    ARCHIVED: 'archived'
} as const;

/**
 * ProjectStatus
 */
export type ProjectStatus = typeof ProjectStatus[keyof typeof ProjectStatus];

/**
 * ProjectTypeCreate
 */
export type ProjectTypeCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Rate
     */
    rate?: number | null;
    default_fee_type?: FeeType | null;
    /**
     * Default Contingency Percentage
     */
    default_contingency_percentage?: number | null;
};

/**
 * ProjectTypeRead
 */
export type ProjectTypeRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Rate
     */
    rate?: number | null;
    default_fee_type?: FeeType | null;
    /**
     * Default Contingency Percentage
     */
    default_contingency_percentage?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Rate
     */
    rate?: number | null;
    /**
     * Forecasted Billable Hours
     */
    forecasted_billable_hours?: number | null;
    /**
     * Actual Hours
     */
    actual_hours?: number | null;
    /**
     * Contingency Percentage
     */
    contingency_percentage?: number | null;
    /**
     * Forecasted Settlement Amount
     */
    forecasted_settlement_amount?: number | null;
    /**
     * Final Settlement Amount
     */
    final_settlement_amount?: number | null;
    /**
     * Forecasted Fee Amount
     */
    forecasted_fee_amount?: number | null;
    fee_type?: FeeType | null;
    status?: ProjectStatus | null;
    /**
     * Updates
     */
    updates?: Array<string> | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Deadline
     */
    deadline?: string | null;
};

/**
 * QuoteCreate
 */
export type QuoteCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Estimated Fee
     */
    estimated_fee?: number | null;
    status?: QuoteStatus;
    /**
     * Expected Start Date
     */
    expected_start_date?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Client Id
     */
    client_id?: number | null;
    /**
     * Lead Id
     */
    lead_id?: number | null;
    /**
     * Lines
     */
    lines?: Array<QuoteLineCreate>;
};

/**
 * QuoteLineCreate
 */
export type QuoteLineCreate = {
    /**
     * Estimated Fee
     */
    estimated_fee?: number | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Project Type Id
     */
    project_type_id: number;
};

/**
 * QuoteLineRead
 */
export type QuoteLineRead = {
    /**
     * Estimated Fee
     */
    estimated_fee?: number | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Quote Id
     */
    quote_id: number;
    /**
     * Project Type Id
     */
    project_type_id: number;
    project_type: ProjectTypeRead;
};

/**
 * QuoteRead
 */
export type QuoteRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Estimated Fee
     */
    estimated_fee?: number | null;
    status?: QuoteStatus;
    /**
     * Expected Start Date
     */
    expected_start_date?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Org Id
     */
    org_id: number;
    /**
     * Client Id
     */
    client_id?: number | null;
    /**
     * Lead Id
     */
    lead_id?: number | null;
    /**
     * Converted Job Id
     */
    converted_job_id?: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Updates
     */
    updates?: Array<unknown> | null;
    client?: ClientReadMinimal | null;
    lead?: LeadReadMinimal | null;
    /**
     * Lines
     */
    lines?: Array<QuoteLineRead>;
};

/**
 * QuoteStatus
 */
export const QuoteStatus = {
    DRAFT: 'draft',
    SENT: 'sent',
    ACCEPTED: 'accepted',
    DECLINED: 'declined'
} as const;

/**
 * QuoteStatus
 */
export type QuoteStatus = typeof QuoteStatus[keyof typeof QuoteStatus];

/**
 * QuoteUpdate
 */
export type QuoteUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Estimated Fee
     */
    estimated_fee?: number | null;
    status?: QuoteStatus | null;
    /**
     * Expected Start Date
     */
    expected_start_date?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Client Id
     */
    client_id?: number | null;
    /**
     * Lead Id
     */
    lead_id?: number | null;
};

/**
 * QuoteUpdateEntry
 */
export type QuoteUpdateEntry = {
    /**
     * Text
     */
    text: string;
};

/**
 * RunCreate
 */
export type RunCreate = {
    /**
     * Job Id
     */
    job_id?: number | null;
    /**
     * Template File Id
     */
    template_file_id: number;
    /**
     * Context File Ids
     */
    context_file_ids: Array<number>;
};

/**
 * RunRead
 */
export type RunRead = {
    status?: RunStatus;
    /**
     * Upload Progress
     */
    upload_progress?: number | null;
    /**
     * Model Responses
     */
    model_responses?: Array<string> | null;
    /**
     * Id
     */
    id: number;
    /**
     * Created By User Id
     */
    created_by_user_id: number;
    /**
     * Org Id
     */
    org_id: number;
    /**
     * Template File Id
     */
    template_file_id: number;
    /**
     * Job Id
     */
    job_id?: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RunStatus
 */
export const RunStatus = {
    IDLE: 'idle',
    PRESIGNING: 'presigning',
    UPLOADING: 'uploading',
    GENERATING: 'generating',
    FINALISING: 'finalising',
    COMPLETED: 'completed',
    ERROR: 'error'
} as const;

/**
 * RunStatus
 */
export type RunStatus = typeof RunStatus[keyof typeof RunStatus];

/**
 * SurveyCreate
 */
export type SurveyCreate = {
    /**
     * Date
     */
    date: string;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Job Id
     */
    job_id: number;
    /**
     * Surveyor Id
     */
    surveyor_id?: number | null;
};

/**
 * SurveyRead
 */
export type SurveyRead = {
    /**
     * Date
     */
    date: string;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Org Id
     */
    org_id: number;
    /**
     * Job Id
     */
    job_id: number;
    /**
     * Surveyor Id
     */
    surveyor_id?: number | null;
    surveyor?: SurveyorRead | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Photo Count
     */
    photo_count?: number;
};

/**
 * SurveyUpdate
 */
export type SurveyUpdate = {
    /**
     * Date
     */
    date?: string | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Surveyor Id
     */
    surveyor_id?: number | null;
};

/**
 * SurveyorRead
 */
export type SurveyorRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
};

/**
 * TaskAssigneeRead
 */
export type TaskAssigneeRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    status?: TaskStatus;
    /**
     * Order
     */
    order?: number;
    /**
     * Estimated Hours
     */
    estimated_hours?: number | null;
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Assignee Id
     */
    assignee_id?: number | null;
};

/**
 * TaskRead
 */
export type TaskRead = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    status?: TaskStatus;
    /**
     * Order
     */
    order?: number;
    /**
     * Estimated Hours
     */
    estimated_hours?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Org Id
     */
    org_id: number;
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Assignee Id
     */
    assignee_id?: number | null;
    assignee?: TaskAssigneeRead | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * TaskReorder
 *
 * Request body for reordering a task
 */
export type TaskReorder = {
    status: TaskStatus;
    /**
     * Order
     */
    order: number;
};

/**
 * TaskStatus
 */
export const TaskStatus = {
    TODO: 'todo',
    IN_PROGRESS: 'in_progress',
    WAITING: 'waiting',
    DONE: 'done'
} as const;

/**
 * TaskStatus
 */
export type TaskStatus = typeof TaskStatus[keyof typeof TaskStatus];

/**
 * TaskUpdate
 */
export type TaskUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    status?: TaskStatus | null;
    /**
     * Order
     */
    order?: number | null;
    /**
     * Estimated Hours
     */
    estimated_hours?: number | null;
    /**
     * Assignee Id
     */
    assignee_id?: number | null;
};

/**
 * TimeEntryCreate
 */
export type TimeEntryCreate = {
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * TimeEntryOut
 */
export type TimeEntryOut = {
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Start Time
     */
    start_time?: string;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Duration Minutes
     */
    duration_minutes?: number | null;
    /**
     * Project Name
     */
    project_name: string;
};

/**
 * UserLogin
 */
export type UserLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: number;
    /**
     * Org Id
     */
    org_id: number;
    role: UserRole;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Org Name
     */
    org_name: string;
};

/**
 * UserRole
 */
export const UserRole = { MEMBER: 'member', ADMIN: 'admin' } as const;

/**
 * UserRole
 */
export type UserRole = typeof UserRole[keyof typeof UserRole];

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: string | null;
    role?: UserRole | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginUserData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginUserError = LoginUserErrors[keyof LoginUserErrors];

export type LoginUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogoutUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutUserError = LogoutUserErrors[keyof LogoutUserErrors];

export type LogoutUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadRunsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/runs/';
};

export type ReadRunsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRunsError = ReadRunsErrors[keyof ReadRunsErrors];

export type ReadRunsResponses = {
    /**
     * Successful Response
     */
    200: RunRead;
};

export type ReadRunsResponse = ReadRunsResponses[keyof ReadRunsResponses];

export type CreateRunData = {
    body: RunCreate;
    path?: never;
    query?: never;
    url: '/runs/';
};

export type CreateRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRunError = CreateRunErrors[keyof CreateRunErrors];

export type CreateRunResponses = {
    /**
     * Successful Response
     */
    200: RunRead;
};

export type CreateRunResponse = CreateRunResponses[keyof CreateRunResponses];

export type ReadRunData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: number;
    };
    query?: never;
    url: '/runs/{run_id}';
};

export type ReadRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRunError = ReadRunErrors[keyof ReadRunErrors];

export type ReadRunResponses = {
    /**
     * Successful Response
     */
    200: RunRead;
};

export type ReadRunResponse = ReadRunResponses[keyof ReadRunResponses];

export type ReadRunArtefactsData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: number;
    };
    query?: never;
    url: '/runs/{run_id}/artefacts';
};

export type ReadRunArtefactsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRunArtefactsError = ReadRunArtefactsErrors[keyof ReadRunArtefactsErrors];

export type ReadRunArtefactsResponses = {
    /**
     * Response Readrunartefacts
     *
     * Successful Response
     */
    200: Array<Artefact>;
};

export type ReadRunArtefactsResponse = ReadRunArtefactsResponses[keyof ReadRunArtefactsResponses];

export type GenerateFileUploadUrlsData = {
    /**
     * Files
     */
    body: Array<FilePresignRequest>;
    path?: never;
    query?: never;
    url: '/store/presign';
};

export type GenerateFileUploadUrlsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateFileUploadUrlsError = GenerateFileUploadUrlsErrors[keyof GenerateFileUploadUrlsErrors];

export type GenerateFileUploadUrlsResponses = {
    /**
     * Response Generatefileuploadurls
     *
     * Successful Response
     */
    200: Array<FilePresignResponse>;
};

export type GenerateFileUploadUrlsResponse = GenerateFileUploadUrlsResponses[keyof GenerateFileUploadUrlsResponses];

export type CreateFileData = {
    body: FileCreate;
    path?: never;
    query?: never;
    url: '/store/single';
};

export type CreateFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFileError = CreateFileErrors[keyof CreateFileErrors];

export type CreateFileResponses = {
    /**
     * Successful Response
     */
    201: FileRead;
};

export type CreateFileResponse = CreateFileResponses[keyof CreateFileResponses];

export type ReadFilesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/store/';
};

export type ReadFilesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFilesError = ReadFilesErrors[keyof ReadFilesErrors];

export type ReadFilesResponses = {
    /**
     * Response Readfiles
     *
     * Successful Response
     */
    200: Array<FileRead>;
};

export type ReadFilesResponse = ReadFilesResponses[keyof ReadFilesResponses];

export type CreateFilesData = {
    /**
     * Files In
     */
    body: Array<FileCreate>;
    path?: never;
    query?: never;
    url: '/store/';
};

export type CreateFilesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFilesError = CreateFilesErrors[keyof CreateFilesErrors];

export type CreateFilesResponses = {
    /**
     * Response Createfiles
     *
     * Successful Response
     */
    201: Array<FileRead>;
};

export type CreateFilesResponse = CreateFilesResponses[keyof CreateFilesResponses];

export type ReadFileData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
    };
    query?: never;
    url: '/store/{file_id}';
};

export type ReadFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFileError = ReadFileErrors[keyof ReadFileErrors];

export type ReadFileResponses = {
    /**
     * Successful Response
     */
    200: FileRead;
};

export type ReadFileResponse = ReadFileResponses[keyof ReadFileResponses];

export type GenerateFileDownloadUrlData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
    };
    query?: {
        /**
         * Inline
         */
        inline?: boolean;
    };
    url: '/store/{file_id}/download';
};

export type GenerateFileDownloadUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateFileDownloadUrlError = GenerateFileDownloadUrlErrors[keyof GenerateFileDownloadUrlErrors];

export type GenerateFileDownloadUrlResponses = {
    /**
     * Response Generatefiledownloadurl
     *
     * Successful Response
     */
    200: string;
};

export type GenerateFileDownloadUrlResponse = GenerateFileDownloadUrlResponses[keyof GenerateFileDownloadUrlResponses];

export type ReadJobsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/jobs/';
};

export type ReadJobsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadJobsError = ReadJobsErrors[keyof ReadJobsErrors];

export type ReadJobsResponses = {
    /**
     * Response Readjobs
     *
     * Successful Response
     */
    200: Array<JobRead>;
};

export type ReadJobsResponse = ReadJobsResponses[keyof ReadJobsResponses];

export type CreateJobData = {
    body: JobCreate;
    path?: never;
    query?: never;
    url: '/jobs/';
};

export type CreateJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateJobError = CreateJobErrors[keyof CreateJobErrors];

export type CreateJobResponses = {
    /**
     * Successful Response
     */
    201: JobRead;
};

export type CreateJobResponse = CreateJobResponses[keyof CreateJobResponses];

export type DeleteJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type DeleteJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteJobError = DeleteJobErrors[keyof DeleteJobErrors];

export type DeleteJobResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteJobResponse = DeleteJobResponses[keyof DeleteJobResponses];

export type ReadJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type ReadJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadJobError = ReadJobErrors[keyof ReadJobErrors];

export type ReadJobResponses = {
    /**
     * Successful Response
     */
    200: JobReadDetail;
};

export type ReadJobResponse = ReadJobResponses[keyof ReadJobResponses];

export type UpdateJobData = {
    body: JobUpdate;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type UpdateJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateJobError = UpdateJobErrors[keyof UpdateJobErrors];

export type UpdateJobResponses = {
    /**
     * Successful Response
     */
    200: JobRead;
};

export type UpdateJobResponse = UpdateJobResponses[keyof UpdateJobResponses];

export type AddJobUpdateData = {
    body: JobUpdateEntry;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/jobs/{job_id}/updates';
};

export type AddJobUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddJobUpdateError = AddJobUpdateErrors[keyof AddJobUpdateErrors];

export type AddJobUpdateResponses = {
    /**
     * Successful Response
     */
    200: JobRead;
};

export type AddJobUpdateResponse = AddJobUpdateResponses[keyof AddJobUpdateResponses];

export type ReadProjectTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects/types';
};

export type ReadProjectTypesResponses = {
    /**
     * Response Readprojecttypes
     *
     * Successful Response
     */
    200: Array<ProjectTypeRead>;
};

export type ReadProjectTypesResponse = ReadProjectTypesResponses[keyof ReadProjectTypesResponses];

export type CreateProjectTypeData = {
    body: ProjectTypeCreate;
    path?: never;
    query?: never;
    url: '/projects/types';
};

export type CreateProjectTypeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectTypeError = CreateProjectTypeErrors[keyof CreateProjectTypeErrors];

export type CreateProjectTypeResponses = {
    /**
     * Successful Response
     */
    201: ProjectTypeRead;
};

export type CreateProjectTypeResponse = CreateProjectTypeResponses[keyof CreateProjectTypeResponses];

export type ReadProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Job Id
         */
        job_id?: number | null;
    };
    url: '/projects/';
};

export type ReadProjectsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProjectsError = ReadProjectsErrors[keyof ReadProjectsErrors];

export type ReadProjectsResponses = {
    /**
     * Response Readprojects
     *
     * Successful Response
     */
    200: Array<ProjectRead>;
};

export type ReadProjectsResponse = ReadProjectsResponses[keyof ReadProjectsResponses];

export type CreateProjectData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/projects/';
};

export type CreateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * Successful Response
     */
    201: ProjectRead;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type DeleteProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type ReadProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type ReadProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProjectError = ReadProjectErrors[keyof ReadProjectErrors];

export type ReadProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectReadDetail;
};

export type ReadProjectResponse = ReadProjectResponses[keyof ReadProjectResponses];

export type UpdateProjectData = {
    body: ProjectUpdate;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type UpdateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectRead;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type RegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/users/';
};

export type RegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type ReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type ReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type ReadUserMeResponse = ReadUserMeResponses[keyof ReadUserMeResponses];

export type UpdateUserMeData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserMeError = UpdateUserMeErrors[keyof UpdateUserMeErrors];

export type UpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateUserMeResponse = UpdateUserMeResponses[keyof UpdateUserMeResponses];

export type ReadClientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/clients/';
};

export type ReadClientsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadClientsError = ReadClientsErrors[keyof ReadClientsErrors];

export type ReadClientsResponses = {
    /**
     * Response Readclients
     *
     * Successful Response
     */
    200: Array<ClientRead>;
};

export type ReadClientsResponse = ReadClientsResponses[keyof ReadClientsResponses];

export type CreateClientData = {
    body: ClientCreate;
    path?: never;
    query?: never;
    url: '/clients/';
};

export type CreateClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateClientError = CreateClientErrors[keyof CreateClientErrors];

export type CreateClientResponses = {
    /**
     * Successful Response
     */
    201: ClientRead;
};

export type CreateClientResponse = CreateClientResponses[keyof CreateClientResponses];

export type DeleteClientData = {
    body?: never;
    path: {
        /**
         * Client Id
         */
        client_id: number;
    };
    query?: never;
    url: '/clients/{client_id}';
};

export type DeleteClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteClientError = DeleteClientErrors[keyof DeleteClientErrors];

export type DeleteClientResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteClientResponse = DeleteClientResponses[keyof DeleteClientResponses];

export type ReadClientData = {
    body?: never;
    path: {
        /**
         * Client Id
         */
        client_id: number;
    };
    query?: never;
    url: '/clients/{client_id}';
};

export type ReadClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadClientError = ReadClientErrors[keyof ReadClientErrors];

export type ReadClientResponses = {
    /**
     * Successful Response
     */
    200: ClientReadDetail;
};

export type ReadClientResponse = ReadClientResponses[keyof ReadClientResponses];

export type UpdateClientData = {
    body: ClientUpdate;
    path: {
        /**
         * Client Id
         */
        client_id: number;
    };
    query?: never;
    url: '/clients/{client_id}';
};

export type UpdateClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateClientError = UpdateClientErrors[keyof UpdateClientErrors];

export type UpdateClientResponses = {
    /**
     * Successful Response
     */
    200: ClientRead;
};

export type UpdateClientResponse = UpdateClientResponses[keyof UpdateClientResponses];

export type CreateClientContactData = {
    body: ClientContactCreate;
    path: {
        /**
         * Client Id
         */
        client_id: number;
    };
    query?: never;
    url: '/clients/{client_id}/contacts';
};

export type CreateClientContactErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateClientContactError = CreateClientContactErrors[keyof CreateClientContactErrors];

export type CreateClientContactResponses = {
    /**
     * Successful Response
     */
    201: ClientContactRead;
};

export type CreateClientContactResponse = CreateClientContactResponses[keyof CreateClientContactResponses];

export type StartTimerTimeStartPostData = {
    body: TimeEntryCreate;
    path?: never;
    query?: never;
    url: '/time/start';
};

export type StartTimerTimeStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartTimerTimeStartPostError = StartTimerTimeStartPostErrors[keyof StartTimerTimeStartPostErrors];

export type StartTimerTimeStartPostResponses = {
    /**
     * Successful Response
     */
    200: TimeEntryOut;
};

export type StartTimerTimeStartPostResponse = StartTimerTimeStartPostResponses[keyof StartTimerTimeStartPostResponses];

export type StopTimerTimeStopPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/time/stop';
};

export type StopTimerTimeStopPostResponses = {
    /**
     * Successful Response
     */
    200: TimeEntryOut;
};

export type StopTimerTimeStopPostResponse = StopTimerTimeStopPostResponses[keyof StopTimerTimeStopPostResponses];

export type GetCurrentTimerTimeCurrentGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/time/current';
};

export type GetCurrentTimerTimeCurrentGetResponses = {
    /**
     * Response Get Current Timer Time Current Get
     *
     * Successful Response
     */
    200: TimeEntryOut | null;
};

export type GetCurrentTimerTimeCurrentGetResponse = GetCurrentTimerTimeCurrentGetResponses[keyof GetCurrentTimerTimeCurrentGetResponses];

export type ReadLeadsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: LeadStatus | null;
    };
    url: '/leads/';
};

export type ReadLeadsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadLeadsError = ReadLeadsErrors[keyof ReadLeadsErrors];

export type ReadLeadsResponses = {
    /**
     * Response Readleads
     *
     * Successful Response
     */
    200: Array<LeadRead>;
};

export type ReadLeadsResponse = ReadLeadsResponses[keyof ReadLeadsResponses];

export type CreateLeadData = {
    body: LeadCreate;
    path?: never;
    query?: never;
    url: '/leads/';
};

export type CreateLeadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLeadError = CreateLeadErrors[keyof CreateLeadErrors];

export type CreateLeadResponses = {
    /**
     * Successful Response
     */
    201: LeadRead;
};

export type CreateLeadResponse = CreateLeadResponses[keyof CreateLeadResponses];

export type DeleteLeadData = {
    body?: never;
    path: {
        /**
         * Lead Id
         */
        lead_id: number;
    };
    query?: never;
    url: '/leads/{lead_id}';
};

export type DeleteLeadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLeadError = DeleteLeadErrors[keyof DeleteLeadErrors];

export type DeleteLeadResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteLeadResponse = DeleteLeadResponses[keyof DeleteLeadResponses];

export type ReadLeadData = {
    body?: never;
    path: {
        /**
         * Lead Id
         */
        lead_id: number;
    };
    query?: never;
    url: '/leads/{lead_id}';
};

export type ReadLeadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadLeadError = ReadLeadErrors[keyof ReadLeadErrors];

export type ReadLeadResponses = {
    /**
     * Successful Response
     */
    200: LeadRead;
};

export type ReadLeadResponse = ReadLeadResponses[keyof ReadLeadResponses];

export type UpdateLeadData = {
    body: LeadUpdate;
    path: {
        /**
         * Lead Id
         */
        lead_id: number;
    };
    query?: never;
    url: '/leads/{lead_id}';
};

export type UpdateLeadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateLeadError = UpdateLeadErrors[keyof UpdateLeadErrors];

export type UpdateLeadResponses = {
    /**
     * Successful Response
     */
    200: LeadRead;
};

export type UpdateLeadResponse = UpdateLeadResponses[keyof UpdateLeadResponses];

export type AddLeadUpdateData = {
    body: LeadUpdateEntry;
    path: {
        /**
         * Lead Id
         */
        lead_id: number;
    };
    query?: never;
    url: '/leads/{lead_id}/updates';
};

export type AddLeadUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddLeadUpdateError = AddLeadUpdateErrors[keyof AddLeadUpdateErrors];

export type AddLeadUpdateResponses = {
    /**
     * Successful Response
     */
    200: LeadRead;
};

export type AddLeadUpdateResponse = AddLeadUpdateResponses[keyof AddLeadUpdateResponses];

export type ConvertLeadData = {
    body?: never;
    path: {
        /**
         * Lead Id
         */
        lead_id: number;
    };
    query?: never;
    url: '/leads/{lead_id}/convert';
};

export type ConvertLeadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConvertLeadError = ConvertLeadErrors[keyof ConvertLeadErrors];

export type ConvertLeadResponses = {
    /**
     * Successful Response
     */
    200: ConvertLeadResponse;
};

export type ConvertLeadResponse2 = ConvertLeadResponses[keyof ConvertLeadResponses];

export type ReadQuotesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: QuoteStatus | null;
        /**
         * Client Id
         */
        client_id?: number | null;
    };
    url: '/quotes/';
};

export type ReadQuotesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadQuotesError = ReadQuotesErrors[keyof ReadQuotesErrors];

export type ReadQuotesResponses = {
    /**
     * Response Readquotes
     *
     * Successful Response
     */
    200: Array<QuoteRead>;
};

export type ReadQuotesResponse = ReadQuotesResponses[keyof ReadQuotesResponses];

export type CreateQuoteData = {
    body: QuoteCreate;
    path?: never;
    query?: never;
    url: '/quotes/';
};

export type CreateQuoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateQuoteError = CreateQuoteErrors[keyof CreateQuoteErrors];

export type CreateQuoteResponses = {
    /**
     * Successful Response
     */
    201: QuoteRead;
};

export type CreateQuoteResponse = CreateQuoteResponses[keyof CreateQuoteResponses];

export type DeleteQuoteData = {
    body?: never;
    path: {
        /**
         * Quote Id
         */
        quote_id: number;
    };
    query?: never;
    url: '/quotes/{quote_id}';
};

export type DeleteQuoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteQuoteError = DeleteQuoteErrors[keyof DeleteQuoteErrors];

export type DeleteQuoteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteQuoteResponse = DeleteQuoteResponses[keyof DeleteQuoteResponses];

export type ReadQuoteData = {
    body?: never;
    path: {
        /**
         * Quote Id
         */
        quote_id: number;
    };
    query?: never;
    url: '/quotes/{quote_id}';
};

export type ReadQuoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadQuoteError = ReadQuoteErrors[keyof ReadQuoteErrors];

export type ReadQuoteResponses = {
    /**
     * Successful Response
     */
    200: QuoteRead;
};

export type ReadQuoteResponse = ReadQuoteResponses[keyof ReadQuoteResponses];

export type UpdateQuoteData = {
    body: QuoteUpdate;
    path: {
        /**
         * Quote Id
         */
        quote_id: number;
    };
    query?: never;
    url: '/quotes/{quote_id}';
};

export type UpdateQuoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateQuoteError = UpdateQuoteErrors[keyof UpdateQuoteErrors];

export type UpdateQuoteResponses = {
    /**
     * Successful Response
     */
    200: QuoteRead;
};

export type UpdateQuoteResponse = UpdateQuoteResponses[keyof UpdateQuoteResponses];

export type AddQuoteLineData = {
    body: QuoteLineCreate;
    path: {
        /**
         * Quote Id
         */
        quote_id: number;
    };
    query?: never;
    url: '/quotes/{quote_id}/lines';
};

export type AddQuoteLineErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddQuoteLineError = AddQuoteLineErrors[keyof AddQuoteLineErrors];

export type AddQuoteLineResponses = {
    /**
     * Successful Response
     */
    201: QuoteRead;
};

export type AddQuoteLineResponse = AddQuoteLineResponses[keyof AddQuoteLineResponses];

export type AddQuoteUpdateData = {
    body: QuoteUpdateEntry;
    path: {
        /**
         * Quote Id
         */
        quote_id: number;
    };
    query?: never;
    url: '/quotes/{quote_id}/updates';
};

export type AddQuoteUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddQuoteUpdateError = AddQuoteUpdateErrors[keyof AddQuoteUpdateErrors];

export type AddQuoteUpdateResponses = {
    /**
     * Successful Response
     */
    200: QuoteRead;
};

export type AddQuoteUpdateResponse = AddQuoteUpdateResponses[keyof AddQuoteUpdateResponses];

export type ConvertQuoteData = {
    body?: never;
    path: {
        /**
         * Quote Id
         */
        quote_id: number;
    };
    query?: never;
    url: '/quotes/{quote_id}/convert';
};

export type ConvertQuoteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConvertQuoteError = ConvertQuoteErrors[keyof ConvertQuoteErrors];

export type ConvertQuoteResponses = {
    /**
     * Successful Response
     */
    200: ConvertQuoteResponse;
};

export type ConvertQuoteResponse2 = ConvertQuoteResponses[keyof ConvertQuoteResponses];

export type ReadSurveysData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Job Id
         */
        job_id?: number | null;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/surveys/';
};

export type ReadSurveysErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadSurveysError = ReadSurveysErrors[keyof ReadSurveysErrors];

export type ReadSurveysResponses = {
    /**
     * Response Readsurveys
     *
     * Successful Response
     */
    200: Array<SurveyRead>;
};

export type ReadSurveysResponse = ReadSurveysResponses[keyof ReadSurveysResponses];

export type CreateSurveyData = {
    body: SurveyCreate;
    path?: never;
    query?: never;
    url: '/surveys/';
};

export type CreateSurveyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSurveyError = CreateSurveyErrors[keyof CreateSurveyErrors];

export type CreateSurveyResponses = {
    /**
     * Successful Response
     */
    201: SurveyRead;
};

export type CreateSurveyResponse = CreateSurveyResponses[keyof CreateSurveyResponses];

export type DeleteSurveyData = {
    body?: never;
    path: {
        /**
         * Survey Id
         */
        survey_id: number;
    };
    query?: never;
    url: '/surveys/{survey_id}';
};

export type DeleteSurveyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSurveyError = DeleteSurveyErrors[keyof DeleteSurveyErrors];

export type DeleteSurveyResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSurveyResponse = DeleteSurveyResponses[keyof DeleteSurveyResponses];

export type ReadSurveyData = {
    body?: never;
    path: {
        /**
         * Survey Id
         */
        survey_id: number;
    };
    query?: never;
    url: '/surveys/{survey_id}';
};

export type ReadSurveyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadSurveyError = ReadSurveyErrors[keyof ReadSurveyErrors];

export type ReadSurveyResponses = {
    /**
     * Successful Response
     */
    200: SurveyRead;
};

export type ReadSurveyResponse = ReadSurveyResponses[keyof ReadSurveyResponses];

export type UpdateSurveyData = {
    body: SurveyUpdate;
    path: {
        /**
         * Survey Id
         */
        survey_id: number;
    };
    query?: never;
    url: '/surveys/{survey_id}';
};

export type UpdateSurveyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSurveyError = UpdateSurveyErrors[keyof UpdateSurveyErrors];

export type UpdateSurveyResponses = {
    /**
     * Successful Response
     */
    200: SurveyRead;
};

export type UpdateSurveyResponse = UpdateSurveyResponses[keyof UpdateSurveyResponses];

export type ReadTasksData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Project Id
         */
        project_id?: number | null;
        /**
         * Status
         */
        status?: TaskStatus | null;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/tasks/';
};

export type ReadTasksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTasksError = ReadTasksErrors[keyof ReadTasksErrors];

export type ReadTasksResponses = {
    /**
     * Response Readtasks
     *
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type ReadTasksResponse = ReadTasksResponses[keyof ReadTasksResponses];

export type CreateTaskData = {
    body: TaskCreate;
    path?: never;
    query?: never;
    url: '/tasks/';
};

export type CreateTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskError = CreateTaskErrors[keyof CreateTaskErrors];

export type CreateTaskResponses = {
    /**
     * Successful Response
     */
    201: TaskRead;
};

export type CreateTaskResponse = CreateTaskResponses[keyof CreateTaskResponses];

export type DeleteTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type DeleteTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTaskError = DeleteTaskErrors[keyof DeleteTaskErrors];

export type DeleteTaskResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTaskResponse = DeleteTaskResponses[keyof DeleteTaskResponses];

export type ReadTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type ReadTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTaskError = ReadTaskErrors[keyof ReadTaskErrors];

export type ReadTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type ReadTaskResponse = ReadTaskResponses[keyof ReadTaskResponses];

export type UpdateTaskData = {
    body: TaskUpdate;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type UpdateTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTaskError = UpdateTaskErrors[keyof UpdateTaskErrors];

export type UpdateTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type UpdateTaskResponse = UpdateTaskResponses[keyof UpdateTaskResponses];

export type ReorderTaskData = {
    body: TaskReorder;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/tasks/{task_id}/reorder';
};

export type ReorderTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReorderTaskError = ReorderTaskErrors[keyof ReorderTaskErrors];

export type ReorderTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type ReorderTaskResponse = ReorderTaskResponses[keyof ReorderTaskResponses];
