// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Artefact
 */
export type Artefact = {
    artefact_type: ArtefactType;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Version
     */
    version: number;
    /**
     * Id
     */
    id?: number | null;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Org Id
     */
    org_id?: number;
    /**
     * Job Id
     */
    job_id?: number | null;
    /**
     * Run Id
     */
    run_id: number;
    /**
     * File Id
     */
    file_id: number;
    /**
     * Preview File Id
     */
    preview_file_id?: number | null;
};

/**
 * ArtefactType
 */
export const ArtefactType = { '.DOCX': '.docx', '.XLSX': '.xlsx' } as const;

/**
 * ArtefactType
 */
export type ArtefactType = typeof ArtefactType[keyof typeof ArtefactType];

/**
 * ClientContactCreate
 */
export type ClientContactCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Role Title
     */
    role_title?: string | null;
};

/**
 * ClientContactRead
 */
export type ClientContactRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Role Title
     */
    role_title?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Client Id
     */
    client_id: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ClientCreate
 */
export type ClientCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Contacts
     */
    contacts?: Array<ClientContactCreate>;
};

/**
 * ClientRead
 */
export type ClientRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Org Id
     */
    org_id: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Contacts
     */
    contacts?: Array<ClientContactRead>;
};

/**
 * ClientUpdate
 */
export type ClientUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Address
     */
    address?: string | null;
};

/**
 * FeeType
 */
export const FeeType = {
    FIXED: 'fixed',
    HOURLY: 'hourly',
    MIXED: 'mixed'
} as const;

/**
 * FeeType
 */
export type FeeType = typeof FeeType[keyof typeof FeeType];

/**
 * FileCreate
 */
export type FileCreate = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Size Bytes
     */
    size_bytes?: number | null;
    /**
     * Storage Key
     */
    storage_key: string;
    /**
     * Org Id
     */
    org_id: number;
    /**
     * Uploaded By User Id
     */
    uploaded_by_user_id?: number | null;
    /**
     * Job Id
     */
    job_id?: number | null;
    /**
     * Run Id
     */
    run_id?: number | null;
    role?: FileRole;
};

/**
 * FilePresignRequest
 */
export type FilePresignRequest = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Size Bytes
     */
    size_bytes?: number | null;
    /**
     * Client Id
     */
    client_id: string;
};

/**
 * FilePresignResponse
 */
export type FilePresignResponse = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Size Bytes
     */
    size_bytes?: number | null;
    /**
     * Client Id
     */
    client_id: string;
    /**
     * Put Url
     */
    put_url: string;
    /**
     * Storage Key
     */
    storage_key: string;
};

/**
 * FileRead
 */
export type FileRead = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Size Bytes
     */
    size_bytes?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Storage Key
     */
    storage_key: string;
    /**
     * Uploaded By User Id
     */
    uploaded_by_user_id: number;
    /**
     * Created At
     */
    created_at: string;
    role: FileRole;
};

/**
 * FileRole
 */
export const FileRole = {
    TEMPLATE: 'template',
    PREVIEW_PDF: 'preview_pdf',
    ARTEFACT: 'artefact',
    INPUT: 'input'
} as const;

/**
 * FileRole
 */
export type FileRole = typeof FileRole[keyof typeof FileRole];

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobCreate
 */
export type JobCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    status?: JobStatus | null;
    /**
     * Client Id
     */
    client_id: number;
    /**
     * Lead User Id
     */
    lead_user_id?: number | null;
};

/**
 * JobRead
 */
export type JobRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    status?: JobStatus | null;
    /**
     * Id
     */
    id: number;
    /**
     * Client Id
     */
    client_id: number;
    /**
     * Created By User Id
     */
    created_by_user_id: number;
    /**
     * Lead User Id
     */
    lead_user_id: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * JobStatus
 */
export const JobStatus = {
    PLANNED: 'planned',
    ACTIVE: 'active',
    COMPLETED: 'completed',
    ARCHIVED: 'archived'
} as const;

/**
 * JobStatus
 */
export type JobStatus = typeof JobStatus[keyof typeof JobStatus];

/**
 * JobUpdate
 */
export type JobUpdate = {
    /**
     * Name
     */
    name: string | null;
    /**
     * Address
     */
    address: string | null;
    status: JobStatus | null;
    /**
     * Client Id
     */
    client_id: number | null;
    /**
     * Lead User Id
     */
    lead_user_id: number | null;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Rate
     */
    rate?: number | null;
    /**
     * Forecasted Billable Hours
     */
    forecasted_billable_hours?: number | null;
    /**
     * Contingency Percentage
     */
    contingency_percentage?: number | null;
    /**
     * Forecasted Settlement Amount
     */
    forecasted_settlement_amount?: number | null;
    /**
     * Forecasted Fee Amount
     */
    forecasted_fee_amount?: number | null;
    fee_type: FeeType;
    status?: ProjectStatus | null;
    /**
     * Updates
     */
    updates?: Array<string> | null;
    /**
     * Lead User Id
     */
    lead_user_id?: number | null;
    /**
     * Job Id
     */
    job_id: number;
    /**
     * Project Type Id
     */
    project_type_id?: number | null;
};

/**
 * ProjectRead
 */
export type ProjectRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Rate
     */
    rate?: number | null;
    /**
     * Forecasted Billable Hours
     */
    forecasted_billable_hours?: number | null;
    /**
     * Contingency Percentage
     */
    contingency_percentage?: number | null;
    /**
     * Forecasted Settlement Amount
     */
    forecasted_settlement_amount?: number | null;
    /**
     * Forecasted Fee Amount
     */
    forecasted_fee_amount?: number | null;
    fee_type: FeeType;
    status?: ProjectStatus | null;
    /**
     * Updates
     */
    updates?: Array<string> | null;
    /**
     * Id
     */
    id: number;
    /**
     * Project Type Id
     */
    project_type_id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProjectStatus
 */
export const ProjectStatus = {
    PLANNED: 'planned',
    ACTIVE: 'active',
    COMPLETED: 'completed',
    ARCHIVED: 'archived'
} as const;

/**
 * ProjectStatus
 */
export type ProjectStatus = typeof ProjectStatus[keyof typeof ProjectStatus];

/**
 * ProjectTypeRead
 */
export type ProjectTypeRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Rate
     */
    rate?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Rate
     */
    rate?: number | null;
    /**
     * Forecasted Billable Hours
     */
    forecasted_billable_hours?: number | null;
    /**
     * Contingency Percentage
     */
    contingency_percentage?: number | null;
    /**
     * Forecasted Settlement Amount
     */
    forecasted_settlement_amount?: number | null;
    /**
     * Forecasted Fee Amount
     */
    forecasted_fee_amount?: number | null;
    fee_type?: FeeType | null;
    status?: ProjectStatus | null;
    /**
     * Updates
     */
    updates?: Array<string> | null;
};

/**
 * RunCreate
 */
export type RunCreate = {
    /**
     * Job Id
     */
    job_id?: number | null;
    /**
     * Template File Id
     */
    template_file_id: number;
    /**
     * Context File Ids
     */
    context_file_ids: Array<number>;
};

/**
 * RunRead
 */
export type RunRead = {
    status?: RunStatus;
    /**
     * Upload Progress
     */
    upload_progress?: number | null;
    /**
     * Model Responses
     */
    model_responses?: Array<string> | null;
    /**
     * Id
     */
    id: number;
    /**
     * Created By User Id
     */
    created_by_user_id: number;
    /**
     * Org Id
     */
    org_id: number;
    /**
     * Template File Id
     */
    template_file_id: number;
    /**
     * Job Id
     */
    job_id?: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RunStatus
 */
export const RunStatus = {
    IDLE: 'idle',
    PRESIGNING: 'presigning',
    UPLOADING: 'uploading',
    GENERATING: 'generating',
    FINALISING: 'finalising',
    COMPLETED: 'completed',
    ERROR: 'error'
} as const;

/**
 * RunStatus
 */
export type RunStatus = typeof RunStatus[keyof typeof RunStatus];

/**
 * UserLogin
 */
export type UserLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: number;
    /**
     * Org Id
     */
    org_id: number;
    role: UserRole;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Org Name
     */
    org_name: string;
};

/**
 * UserRole
 */
export const UserRole = { MEMBER: 'member', ADMIN: 'admin' } as const;

/**
 * UserRole
 */
export type UserRole = typeof UserRole[keyof typeof UserRole];

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: string | null;
    role?: UserRole | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginUserData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginUserError = LoginUserErrors[keyof LoginUserErrors];

export type LoginUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogoutUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutUserError = LogoutUserErrors[keyof LogoutUserErrors];

export type LogoutUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadRunsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/runs/';
};

export type ReadRunsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRunsError = ReadRunsErrors[keyof ReadRunsErrors];

export type ReadRunsResponses = {
    /**
     * Successful Response
     */
    200: RunRead;
};

export type ReadRunsResponse = ReadRunsResponses[keyof ReadRunsResponses];

export type CreateRunData = {
    body: RunCreate;
    path?: never;
    query?: never;
    url: '/runs/';
};

export type CreateRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRunError = CreateRunErrors[keyof CreateRunErrors];

export type CreateRunResponses = {
    /**
     * Successful Response
     */
    200: RunRead;
};

export type CreateRunResponse = CreateRunResponses[keyof CreateRunResponses];

export type ReadRunData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: number;
    };
    query?: never;
    url: '/runs/{run_id}';
};

export type ReadRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRunError = ReadRunErrors[keyof ReadRunErrors];

export type ReadRunResponses = {
    /**
     * Successful Response
     */
    200: RunRead;
};

export type ReadRunResponse = ReadRunResponses[keyof ReadRunResponses];

export type ReadRunArtefactsData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: number;
    };
    query?: never;
    url: '/runs/{run_id}/artefacts';
};

export type ReadRunArtefactsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRunArtefactsError = ReadRunArtefactsErrors[keyof ReadRunArtefactsErrors];

export type ReadRunArtefactsResponses = {
    /**
     * Response Readrunartefacts
     *
     * Successful Response
     */
    200: Array<Artefact>;
};

export type ReadRunArtefactsResponse = ReadRunArtefactsResponses[keyof ReadRunArtefactsResponses];

export type GenerateFileUploadUrlsData = {
    /**
     * Files
     */
    body: Array<FilePresignRequest>;
    path?: never;
    query?: never;
    url: '/store/presign';
};

export type GenerateFileUploadUrlsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateFileUploadUrlsError = GenerateFileUploadUrlsErrors[keyof GenerateFileUploadUrlsErrors];

export type GenerateFileUploadUrlsResponses = {
    /**
     * Response Generatefileuploadurls
     *
     * Successful Response
     */
    200: Array<FilePresignResponse>;
};

export type GenerateFileUploadUrlsResponse = GenerateFileUploadUrlsResponses[keyof GenerateFileUploadUrlsResponses];

export type CreateFileData = {
    body: FileCreate;
    path?: never;
    query?: never;
    url: '/store/single';
};

export type CreateFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFileError = CreateFileErrors[keyof CreateFileErrors];

export type CreateFileResponses = {
    /**
     * Successful Response
     */
    201: FileRead;
};

export type CreateFileResponse = CreateFileResponses[keyof CreateFileResponses];

export type ReadFilesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/store/';
};

export type ReadFilesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFilesError = ReadFilesErrors[keyof ReadFilesErrors];

export type ReadFilesResponses = {
    /**
     * Response Readfiles
     *
     * Successful Response
     */
    200: Array<FileRead>;
};

export type ReadFilesResponse = ReadFilesResponses[keyof ReadFilesResponses];

export type CreateFilesData = {
    /**
     * Files In
     */
    body: Array<FileCreate>;
    path?: never;
    query?: never;
    url: '/store/';
};

export type CreateFilesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFilesError = CreateFilesErrors[keyof CreateFilesErrors];

export type CreateFilesResponses = {
    /**
     * Response Createfiles
     *
     * Successful Response
     */
    201: Array<FileRead>;
};

export type CreateFilesResponse = CreateFilesResponses[keyof CreateFilesResponses];

export type ReadFileData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
    };
    query?: never;
    url: '/store/{file_id}';
};

export type ReadFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFileError = ReadFileErrors[keyof ReadFileErrors];

export type ReadFileResponses = {
    /**
     * Successful Response
     */
    200: FileRead;
};

export type ReadFileResponse = ReadFileResponses[keyof ReadFileResponses];

export type GenerateFileDownloadUrlData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
    };
    query?: {
        /**
         * Inline
         */
        inline?: boolean;
    };
    url: '/store/{file_id}/download';
};

export type GenerateFileDownloadUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateFileDownloadUrlError = GenerateFileDownloadUrlErrors[keyof GenerateFileDownloadUrlErrors];

export type GenerateFileDownloadUrlResponses = {
    /**
     * Response Generatefiledownloadurl
     *
     * Successful Response
     */
    200: string;
};

export type GenerateFileDownloadUrlResponse = GenerateFileDownloadUrlResponses[keyof GenerateFileDownloadUrlResponses];

export type ReadJobsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/jobs/';
};

export type ReadJobsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadJobsError = ReadJobsErrors[keyof ReadJobsErrors];

export type ReadJobsResponses = {
    /**
     * Response Readjobs
     *
     * Successful Response
     */
    200: Array<JobRead>;
};

export type ReadJobsResponse = ReadJobsResponses[keyof ReadJobsResponses];

export type CreateJobData = {
    body: JobCreate;
    path?: never;
    query?: never;
    url: '/jobs/';
};

export type CreateJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateJobError = CreateJobErrors[keyof CreateJobErrors];

export type CreateJobResponses = {
    /**
     * Successful Response
     */
    201: JobRead;
};

export type CreateJobResponse = CreateJobResponses[keyof CreateJobResponses];

export type DeleteJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type DeleteJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteJobError = DeleteJobErrors[keyof DeleteJobErrors];

export type DeleteJobResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteJobResponse = DeleteJobResponses[keyof DeleteJobResponses];

export type ReadJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type ReadJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadJobError = ReadJobErrors[keyof ReadJobErrors];

export type ReadJobResponses = {
    /**
     * Successful Response
     */
    200: JobRead;
};

export type ReadJobResponse = ReadJobResponses[keyof ReadJobResponses];

export type UpdateJobData = {
    body: JobUpdate;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type UpdateJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateJobError = UpdateJobErrors[keyof UpdateJobErrors];

export type UpdateJobResponses = {
    /**
     * Successful Response
     */
    200: JobRead;
};

export type UpdateJobResponse = UpdateJobResponses[keyof UpdateJobResponses];

export type ReadProjectTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects/types';
};

export type ReadProjectTypesResponses = {
    /**
     * Response Readprojecttypes
     *
     * Successful Response
     */
    200: Array<ProjectTypeRead>;
};

export type ReadProjectTypesResponse = ReadProjectTypesResponses[keyof ReadProjectTypesResponses];

export type ReadProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Job Id
         */
        job_id?: number | null;
    };
    url: '/projects/';
};

export type ReadProjectsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProjectsError = ReadProjectsErrors[keyof ReadProjectsErrors];

export type ReadProjectsResponses = {
    /**
     * Response Readprojects
     *
     * Successful Response
     */
    200: Array<ProjectRead>;
};

export type ReadProjectsResponse = ReadProjectsResponses[keyof ReadProjectsResponses];

export type CreateProjectData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/projects/';
};

export type CreateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * Successful Response
     */
    201: ProjectRead;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type DeleteProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type ReadProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type ReadProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProjectError = ReadProjectErrors[keyof ReadProjectErrors];

export type ReadProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectRead;
};

export type ReadProjectResponse = ReadProjectResponses[keyof ReadProjectResponses];

export type UpdateProjectData = {
    body: ProjectUpdate;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type UpdateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectRead;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type RegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/users/';
};

export type RegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type ReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type ReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type ReadUserMeResponse = ReadUserMeResponses[keyof ReadUserMeResponses];

export type UpdateUserMeData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserMeError = UpdateUserMeErrors[keyof UpdateUserMeErrors];

export type UpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateUserMeResponse = UpdateUserMeResponses[keyof UpdateUserMeResponses];

export type ReadClientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/clients/';
};

export type ReadClientsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadClientsError = ReadClientsErrors[keyof ReadClientsErrors];

export type ReadClientsResponses = {
    /**
     * Response Readclients
     *
     * Successful Response
     */
    200: Array<ClientRead>;
};

export type ReadClientsResponse = ReadClientsResponses[keyof ReadClientsResponses];

export type CreateClientData = {
    body: ClientCreate;
    path?: never;
    query?: never;
    url: '/clients/';
};

export type CreateClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateClientError = CreateClientErrors[keyof CreateClientErrors];

export type CreateClientResponses = {
    /**
     * Successful Response
     */
    201: ClientRead;
};

export type CreateClientResponse = CreateClientResponses[keyof CreateClientResponses];

export type DeleteClientData = {
    body?: never;
    path: {
        /**
         * Client Id
         */
        client_id: number;
    };
    query?: never;
    url: '/clients/{client_id}';
};

export type DeleteClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteClientError = DeleteClientErrors[keyof DeleteClientErrors];

export type DeleteClientResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteClientResponse = DeleteClientResponses[keyof DeleteClientResponses];

export type ReadClientData = {
    body?: never;
    path: {
        /**
         * Client Id
         */
        client_id: number;
    };
    query?: never;
    url: '/clients/{client_id}';
};

export type ReadClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadClientError = ReadClientErrors[keyof ReadClientErrors];

export type ReadClientResponses = {
    /**
     * Successful Response
     */
    200: ClientRead;
};

export type ReadClientResponse = ReadClientResponses[keyof ReadClientResponses];

export type UpdateClientData = {
    body: ClientUpdate;
    path: {
        /**
         * Client Id
         */
        client_id: number;
    };
    query?: never;
    url: '/clients/{client_id}';
};

export type UpdateClientErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateClientError = UpdateClientErrors[keyof UpdateClientErrors];

export type UpdateClientResponses = {
    /**
     * Successful Response
     */
    200: ClientRead;
};

export type UpdateClientResponse = UpdateClientResponses[keyof UpdateClientResponses];
