// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createJob, createProjectJobsProjectsPost, getCurrentUser, getJob, getJobs, getLatestArtefact, getProjectJobsProjectsProjectIdGet, getProjectTypesJobsProjectTypesGet, getRunStatus, login, logout, type Options, presignUploads, readUserMeUsersMeGet, register, registerFiles, startRun, updateUserMeUsersMePatch } from '../sdk.gen';
import type { CreateJobData, CreateJobError, CreateJobResponse, CreateProjectJobsProjectsPostData, CreateProjectJobsProjectsPostError, CreateProjectJobsProjectsPostResponse, GetCurrentUserData, GetCurrentUserResponse, GetJobData, GetJobError, GetJobResponse, GetJobsData, GetJobsError, GetJobsResponse, GetLatestArtefactData, GetLatestArtefactError, GetLatestArtefactResponse, GetProjectJobsProjectsProjectIdGetData, GetProjectJobsProjectsProjectIdGetError, GetProjectJobsProjectsProjectIdGetResponse, GetProjectTypesJobsProjectTypesGetData, GetProjectTypesJobsProjectTypesGetResponse, GetRunStatusData, GetRunStatusError, GetRunStatusResponse, LoginData, LoginError, LoginResponse, LogoutData, PresignUploadsData, PresignUploadsError, PresignUploadsResponse, ReadUserMeUsersMeGetData, ReadUserMeUsersMeGetResponse, RegisterData, RegisterError, RegisterFilesData, RegisterFilesError, RegisterFilesResponse2, RegisterResponse, StartRunData, StartRunError, StartRunResponse2, UpdateUserMeUsersMePatchData, UpdateUserMeUsersMePatchError, UpdateUserMeUsersMePatchResponse } from '../types.gen';

/**
 * Register
 */
export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, RegisterError, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, RegisterError, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<unknown, DefaultError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) => createQueryKey('getCurrentUser', options);

/**
 * Me
 */
export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) => queryOptions<GetCurrentUserResponse, DefaultError, GetCurrentUserResponse, ReturnType<typeof getCurrentUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentUserQueryKey(options)
});

/**
 * Start Run
 *
 * Creates a Run and starts processing in background.
 */
export const startRunMutation = (options?: Partial<Options<StartRunData>>): UseMutationOptions<StartRunResponse2, StartRunError, Options<StartRunData>> => {
    const mutationOptions: UseMutationOptions<StartRunResponse2, StartRunError, Options<StartRunData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await startRun({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRunStatusQueryKey = (options: Options<GetRunStatusData>) => createQueryKey('getRunStatus', options);

/**
 * Get Run Status
 *
 * Returns the current status, progress, and model responses of a run.
 */
export const getRunStatusOptions = (options: Options<GetRunStatusData>) => queryOptions<GetRunStatusResponse, GetRunStatusError, GetRunStatusResponse, ReturnType<typeof getRunStatusQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRunStatus({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRunStatusQueryKey(options)
});

export const getLatestArtefactQueryKey = (options: Options<GetLatestArtefactData>) => createQueryKey('getLatestArtefact', options);

/**
 * Get Download Url
 *
 * Return a presigned download URL for the generated document.
 */
export const getLatestArtefactOptions = (options: Options<GetLatestArtefactData>) => queryOptions<GetLatestArtefactResponse, GetLatestArtefactError, GetLatestArtefactResponse, ReturnType<typeof getLatestArtefactQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLatestArtefact({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLatestArtefactQueryKey(options)
});

/**
 * Presign Uploads
 *
 * Generate presigned URLs for uploading files.
 */
export const presignUploadsMutation = (options?: Partial<Options<PresignUploadsData>>): UseMutationOptions<PresignUploadsResponse, PresignUploadsError, Options<PresignUploadsData>> => {
    const mutationOptions: UseMutationOptions<PresignUploadsResponse, PresignUploadsError, Options<PresignUploadsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await presignUploads({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register Files
 *
 * Register uploaded files in the database after verification.
 */
export const registerFilesMutation = (options?: Partial<Options<RegisterFilesData>>): UseMutationOptions<RegisterFilesResponse2, RegisterFilesError, Options<RegisterFilesData>> => {
    const mutationOptions: UseMutationOptions<RegisterFilesResponse2, RegisterFilesError, Options<RegisterFilesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await registerFiles({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create Job
 *
 * Create a new job.
 */
export const createJobMutation = (options?: Partial<Options<CreateJobData>>): UseMutationOptions<CreateJobResponse, CreateJobError, Options<CreateJobData>> => {
    const mutationOptions: UseMutationOptions<CreateJobResponse, CreateJobError, Options<CreateJobData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createJob({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getJobsQueryKey = (options?: Options<GetJobsData>) => createQueryKey('getJobs', options);

/**
 * Get Jobs For User
 *
 * Get jobs created by the current user with pagination.
 */
export const getJobsOptions = (options?: Options<GetJobsData>) => queryOptions<GetJobsResponse, GetJobsError, GetJobsResponse, ReturnType<typeof getJobsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getJobs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getJobsInfiniteQueryKey = (options?: Options<GetJobsData>): QueryKey<Options<GetJobsData>> => createQueryKey('getJobs', options, true);

/**
 * Get Jobs For User
 *
 * Get jobs created by the current user with pagination.
 */
export const getJobsInfiniteOptions = (options?: Options<GetJobsData>) => infiniteQueryOptions<GetJobsResponse, GetJobsError, InfiniteData<GetJobsResponse>, QueryKey<Options<GetJobsData>>, number | Pick<QueryKey<Options<GetJobsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetJobsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                start: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getJobs({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobsInfiniteQueryKey(options)
});

export const getJobQueryKey = (options: Options<GetJobData>) => createQueryKey('getJob', options);

/**
 * Get Job
 *
 * Get job details.
 */
export const getJobOptions = (options: Options<GetJobData>) => queryOptions<GetJobResponse, GetJobError, GetJobResponse, ReturnType<typeof getJobQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getJob({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobQueryKey(options)
});

/**
 * Create Project
 *
 * Create a new project.
 */
export const createProjectJobsProjectsPostMutation = (options?: Partial<Options<CreateProjectJobsProjectsPostData>>): UseMutationOptions<CreateProjectJobsProjectsPostResponse, CreateProjectJobsProjectsPostError, Options<CreateProjectJobsProjectsPostData>> => {
    const mutationOptions: UseMutationOptions<CreateProjectJobsProjectsPostResponse, CreateProjectJobsProjectsPostError, Options<CreateProjectJobsProjectsPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createProjectJobsProjectsPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getProjectJobsProjectsProjectIdGetQueryKey = (options: Options<GetProjectJobsProjectsProjectIdGetData>) => createQueryKey('getProjectJobsProjectsProjectIdGet', options);

/**
 * Get Project
 *
 * Get project details.
 */
export const getProjectJobsProjectsProjectIdGetOptions = (options: Options<GetProjectJobsProjectsProjectIdGetData>) => queryOptions<GetProjectJobsProjectsProjectIdGetResponse, GetProjectJobsProjectsProjectIdGetError, GetProjectJobsProjectsProjectIdGetResponse, ReturnType<typeof getProjectJobsProjectsProjectIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProjectJobsProjectsProjectIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProjectJobsProjectsProjectIdGetQueryKey(options)
});

export const getProjectTypesJobsProjectTypesGetQueryKey = (options?: Options<GetProjectTypesJobsProjectTypesGetData>) => createQueryKey('getProjectTypesJobsProjectTypesGet', options);

/**
 * Get Project Types
 *
 * Get all project types.
 */
export const getProjectTypesJobsProjectTypesGetOptions = (options?: Options<GetProjectTypesJobsProjectTypesGetData>) => queryOptions<GetProjectTypesJobsProjectTypesGetResponse, DefaultError, GetProjectTypesJobsProjectTypesGetResponse, ReturnType<typeof getProjectTypesJobsProjectTypesGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProjectTypesJobsProjectTypesGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProjectTypesJobsProjectTypesGetQueryKey(options)
});

export const readUserMeUsersMeGetQueryKey = (options?: Options<ReadUserMeUsersMeGetData>) => createQueryKey('readUserMeUsersMeGet', options);

/**
 * Read User Me
 *
 * Get current user.
 */
export const readUserMeUsersMeGetOptions = (options?: Options<ReadUserMeUsersMeGetData>) => queryOptions<ReadUserMeUsersMeGetResponse, DefaultError, ReadUserMeUsersMeGetResponse, ReturnType<typeof readUserMeUsersMeGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await readUserMeUsersMeGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: readUserMeUsersMeGetQueryKey(options)
});

/**
 * Update User Me
 *
 * Update current user.
 */
export const updateUserMeUsersMePatchMutation = (options?: Partial<Options<UpdateUserMeUsersMePatchData>>): UseMutationOptions<UpdateUserMeUsersMePatchResponse, UpdateUserMeUsersMePatchError, Options<UpdateUserMeUsersMePatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateUserMeUsersMePatchResponse, UpdateUserMeUsersMePatchError, Options<UpdateUserMeUsersMePatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateUserMeUsersMePatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
