// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ClientContactCreate
 */
export type ClientContactCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Role Title
     */
    role_title?: string | null;
};

/**
 * ClientContactRead
 */
export type ClientContactRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Role Title
     */
    role_title?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Client Id
     */
    client_id: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ClientCreate
 *
 * Attributes required to create a new Client.
 */
export type ClientCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Contacts
     */
    contacts?: Array<ClientContactCreate>;
};

/**
 * ClientRead
 *
 * For reading Client metadata.
 */
export type ClientRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Org Id
     */
    org_id?: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Contacts
     */
    contacts?: Array<ClientContactRead>;
};

/**
 * FeeType
 */
export const FeeType = {
    FIXED: 'fixed',
    HOURLY: 'hourly',
    MIXED: 'mixed'
} as const;

/**
 * FeeType
 */
export type FeeType = typeof FeeType[keyof typeof FeeType];

/**
 * FileInput
 *
 * Attributes for a file that has been uploaded (has a key).
 */
export type FileInput = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    role: FileRole;
    /**
     * Storage Key
     */
    storage_key: string;
};

/**
 * FilePresign
 *
 * Attributes required to request a presigned URL.
 */
export type FilePresign = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    role: FileRole;
};

/**
 * FileRead
 *
 * DTO for file metadata passed from frontend to backend services.
 */
export type FileRead = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    role: FileRole;
    /**
     * Storage Key
     */
    storage_key: string;
    /**
     * Id
     */
    id: number;
    /**
     * Owner User Id
     */
    owner_user_id: number;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * FileRole
 */
export const FileRole = {
    TEMPLATE: 'template',
    PREVIEW_PDF: 'preview_pdf',
    ARTEFACT: 'artefact',
    INPUT: 'input'
} as const;

/**
 * FileRole
 */
export type FileRole = typeof FileRole[keyof typeof FileRole];

/**
 * GetPresignPutsRequest
 */
export type GetPresignPutsRequest = {
    /**
     * Files
     */
    files: Array<FilePresign>;
};

/**
 * GetPresignPutsResponse
 */
export type GetPresignPutsResponse = {
    /**
     * Puts
     */
    puts: Array<PresignedPut>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobClientRead
 */
export type JobClientRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
};

/**
 * JobCreate
 *
 * For creating new Jobs.
 */
export type JobCreate = {
    /**
     * Org Id
     */
    org_id?: number | null;
    /**
     * Client Id
     */
    client_id: number;
    /**
     * Created By User Id
     */
    created_by_user_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Lead User Id
     */
    lead_user_id?: number | null;
    /**
     * Address
     */
    address?: string | null;
    status?: JobStatus | null;
};

/**
 * JobDetailRead
 *
 * For reading nested Job data, E.g. in a full page job view
 */
export type JobDetailRead = {
    /**
     * Org Id
     */
    org_id?: number | null;
    /**
     * Client Id
     */
    client_id: number;
    /**
     * Created By User Id
     */
    created_by_user_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: number;
    /**
     * Lead User Id
     */
    lead_user_id: number | null;
    /**
     * Address
     */
    address: string | null;
    /**
     * Status
     */
    status: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string | null;
    client: ClientRead;
    org: OrgRead;
    created_by_user: UserRead;
    lead_user: UserRead | null;
    /**
     * Projects
     */
    projects?: Array<ProjectRead>;
    /**
     * Job Files
     */
    job_files?: Array<JobFileRead>;
};

/**
 * JobFileRead
 *
 * For reading JobFile data, we always want full file data.
 */
export type JobFileRead = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    role: FileRole;
    /**
     * Id
     */
    id: number;
    /**
     * Job Id
     */
    job_id: number;
    file: FileRead;
    /**
     * Added By User Name
     */
    added_by_user_name: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * JobRead
 *
 * For reading Job metadata. E.g. in a list or table view,
 */
export type JobRead = {
    /**
     * Org Id
     */
    org_id?: number | null;
    /**
     * Client Id
     */
    client_id: number;
    /**
     * Created By User Id
     */
    created_by_user_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: number;
    /**
     * Lead User Id
     */
    lead_user_id: number | null;
    /**
     * Address
     */
    address: string | null;
    /**
     * Status
     */
    status: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string | null;
    client: JobClientRead;
};

/**
 * JobStatus
 */
export const JobStatus = {
    PLANNED: 'planned',
    ACTIVE: 'active',
    COMPLETED: 'completed',
    ARCHIVED: 'archived'
} as const;

/**
 * JobStatus
 */
export type JobStatus = typeof JobStatus[keyof typeof JobStatus];

/**
 * LatestArtefactResponse
 */
export type LatestArtefactResponse = {
    /**
     * Download Url
     */
    download_url: string;
    /**
     * Preview Url
     */
    preview_url: string;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * MessageResponse
 */
export type MessageResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * OrgRead
 *
 * For reading Org metadata.
 */
export type OrgRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PresignedPut
 */
export type PresignedPut = {
    file: FileInput;
    /**
     * Put Url
     */
    put_url: string;
};

/**
 * ProjectCreate
 *
 * For creating new Projects.
 */
export type ProjectCreate = {
    /**
     * Job Id
     */
    job_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Project Type Id
     */
    project_type_id?: number | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Rate
     */
    rate?: number | null;
    /**
     * Forecasted Billable Hours
     */
    forecasted_billable_hours?: number | null;
    /**
     * Contingency Percentage
     */
    contingency_percentage?: number | null;
    /**
     * Forecasted Settlement Amount
     */
    forecasted_settlement_amount?: number | null;
    /**
     * Forecasted Fee Amount
     */
    forecasted_fee_amount?: number | null;
    fee_type?: FeeType | null;
    status?: ProjectStatus | null;
};

/**
 * ProjectDetailRead
 *
 * For reading nested Project data.
 */
export type ProjectDetailRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Job Id
     */
    job_id: number;
    /**
     * Job Name
     */
    job_name: string;
    /**
     * Project Type Id
     */
    project_type_id: number;
    /**
     * Project Type Name
     */
    project_type_name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string | null;
    status: ProjectStatus | null;
    job: JobRead;
    project_type: ProjectTypeRead;
    /**
     * Rate
     */
    rate?: number | null;
    /**
     * Forecasted Billable Hours
     */
    forecasted_billable_hours?: number | null;
    /**
     * Contingency Percentage
     */
    contingency_percentage?: number | null;
    /**
     * Forecasted Settlement Amount
     */
    forecasted_settlement_amount?: number | null;
    /**
     * Forecasted Fee Amount
     */
    forecasted_fee_amount?: number | null;
    fee_type?: FeeType | null;
};

/**
 * ProjectRead
 *
 * For reading Project metadata.
 */
export type ProjectRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Job Id
     */
    job_id: number;
    /**
     * Job Name
     */
    job_name: string;
    /**
     * Project Type Id
     */
    project_type_id: number;
    /**
     * Project Type Name
     */
    project_type_name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string | null;
    status: ProjectStatus | null;
};

/**
 * ProjectStatus
 */
export const ProjectStatus = {
    PLANNED: 'planned',
    ACTIVE: 'active',
    COMPLETED: 'completed',
    ARCHIVED: 'archived'
} as const;

/**
 * ProjectStatus
 */
export type ProjectStatus = typeof ProjectStatus[keyof typeof ProjectStatus];

/**
 * ProjectTypeRead
 *
 * For reading ProjectType metadata.
 */
export type ProjectTypeRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Rate
     */
    rate?: number | null;
};

/**
 * RegisterFilesRequest
 */
export type RegisterFilesRequest = {
    /**
     * Files
     */
    files: Array<FileInput>;
};

/**
 * RegisterFilesResponse
 */
export type RegisterFilesResponse = {
    /**
     * Files
     */
    files: Array<FileRead>;
};

/**
 * RunStatusResponse
 */
export type RunStatusResponse = {
    /**
     * Run Id
     */
    run_id: number;
    /**
     * Status
     */
    status: string;
    /**
     * Upload Progress
     */
    upload_progress: number;
    /**
     * Model Responses
     */
    model_responses: Array<string>;
};

/**
 * SignupRequest
 */
export type SignupRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Name
     */
    name: string;
};

/**
 * StartRunRequest
 */
export type StartRunRequest = {
    /**
     * Template Id
     */
    template_id: number;
    /**
     * Context File Ids
     */
    context_file_ids?: Array<number>;
    /**
     * Job Id
     */
    job_id?: number | null;
};

/**
 * StartRunResponse
 */
export type StartRunResponse = {
    /**
     * Run Id
     */
    run_id: number;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Role
     */
    role?: 'member' | 'admin' | null;
    /**
     * Id
     */
    id: number;
    /**
     * Org Id
     */
    org_id?: number | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Role
     */
    role?: 'member' | 'admin' | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RegisterData = {
    body: SignupRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    201: MessageResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: MessageResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type StartRunData = {
    body: StartRunRequest;
    path?: never;
    query?: never;
    url: '/generate/start_run';
};

export type StartRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartRunError = StartRunErrors[keyof StartRunErrors];

export type StartRunResponses = {
    /**
     * Successful Response
     */
    200: StartRunResponse;
};

export type StartRunResponse2 = StartRunResponses[keyof StartRunResponses];

export type GetRunStatusData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: number;
    };
    query?: never;
    url: '/generate/status/{run_id}';
};

export type GetRunStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunStatusError = GetRunStatusErrors[keyof GetRunStatusErrors];

export type GetRunStatusResponses = {
    /**
     * Successful Response
     */
    200: RunStatusResponse;
};

export type GetRunStatusResponse = GetRunStatusResponses[keyof GetRunStatusResponses];

export type GetLatestArtefactData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: number;
    };
    query?: never;
    url: '/generate/latest_artefact/{run_id}';
};

export type GetLatestArtefactErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLatestArtefactError = GetLatestArtefactErrors[keyof GetLatestArtefactErrors];

export type GetLatestArtefactResponses = {
    /**
     * Successful Response
     */
    200: LatestArtefactResponse;
};

export type GetLatestArtefactResponse = GetLatestArtefactResponses[keyof GetLatestArtefactResponses];

export type PresignUploadsData = {
    body: GetPresignPutsRequest;
    path?: never;
    query?: never;
    url: '/store/presign_uploads';
};

export type PresignUploadsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PresignUploadsError = PresignUploadsErrors[keyof PresignUploadsErrors];

export type PresignUploadsResponses = {
    /**
     * Successful Response
     */
    200: GetPresignPutsResponse;
};

export type PresignUploadsResponse = PresignUploadsResponses[keyof PresignUploadsResponses];

export type RegisterFilesData = {
    body: RegisterFilesRequest;
    path?: never;
    query?: never;
    url: '/store/register';
};

export type RegisterFilesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterFilesError = RegisterFilesErrors[keyof RegisterFilesErrors];

export type RegisterFilesResponses = {
    /**
     * Successful Response
     */
    200: RegisterFilesResponse;
};

export type RegisterFilesResponse2 = RegisterFilesResponses[keyof RegisterFilesResponses];

export type CreateJobData = {
    body: JobCreate;
    path?: never;
    query?: never;
    url: '/jobs/jobs';
};

export type CreateJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateJobError = CreateJobErrors[keyof CreateJobErrors];

export type CreateJobResponses = {
    /**
     * Successful Response
     */
    200: JobRead;
};

export type CreateJobResponse = CreateJobResponses[keyof CreateJobResponses];

export type GetJobsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start
         */
        start?: number;
        /**
         * End
         */
        end?: number;
    };
    url: '/jobs/jobs/get_jobs_for_user';
};

export type GetJobsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobsError = GetJobsErrors[keyof GetJobsErrors];

export type GetJobsResponses = {
    /**
     * Response Getjobs
     *
     * Successful Response
     */
    200: Array<JobRead>;
};

export type GetJobsResponse = GetJobsResponses[keyof GetJobsResponses];

export type GetJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/jobs/jobs/{job_id}';
};

export type GetJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * Successful Response
     */
    200: JobDetailRead;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type CreateProjectJobsProjectsPostData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/jobs/projects';
};

export type CreateProjectJobsProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectJobsProjectsPostError = CreateProjectJobsProjectsPostErrors[keyof CreateProjectJobsProjectsPostErrors];

export type CreateProjectJobsProjectsPostResponses = {
    /**
     * Successful Response
     */
    200: ProjectRead;
};

export type CreateProjectJobsProjectsPostResponse = CreateProjectJobsProjectsPostResponses[keyof CreateProjectJobsProjectsPostResponses];

export type GetProjectJobsProjectsProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/jobs/projects/{project_id}';
};

export type GetProjectJobsProjectsProjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectJobsProjectsProjectIdGetError = GetProjectJobsProjectsProjectIdGetErrors[keyof GetProjectJobsProjectsProjectIdGetErrors];

export type GetProjectJobsProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectDetailRead;
};

export type GetProjectJobsProjectsProjectIdGetResponse = GetProjectJobsProjectsProjectIdGetResponses[keyof GetProjectJobsProjectsProjectIdGetResponses];

export type GetProjectTypesJobsProjectTypesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/jobs/project_types';
};

export type GetProjectTypesJobsProjectTypesGetResponses = {
    /**
     * Response Get Project Types Jobs Project Types Get
     *
     * Successful Response
     */
    200: Array<ProjectTypeRead>;
};

export type GetProjectTypesJobsProjectTypesGetResponse = GetProjectTypesJobsProjectTypesGetResponses[keyof GetProjectTypesJobsProjectTypesGetResponses];

export type GetClientsJobsClientsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/jobs/clients';
};

export type GetClientsJobsClientsGetResponses = {
    /**
     * Response Get Clients Jobs Clients Get
     *
     * Successful Response
     */
    200: Array<ClientRead>;
};

export type GetClientsJobsClientsGetResponse = GetClientsJobsClientsGetResponses[keyof GetClientsJobsClientsGetResponses];

export type ReadUserMeUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type ReadUserMeUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type ReadUserMeUsersMeGetResponse = ReadUserMeUsersMeGetResponses[keyof ReadUserMeUsersMeGetResponses];

export type UpdateUserMeUsersMePatchData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UpdateUserMeUsersMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserMeUsersMePatchError = UpdateUserMeUsersMePatchErrors[keyof UpdateUserMeUsersMePatchErrors];

export type UpdateUserMeUsersMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateUserMeUsersMePatchResponse = UpdateUserMeUsersMePatchResponses[keyof UpdateUserMeUsersMePatchResponses];

export type GetUsersUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/';
};

export type GetUsersUsersGetResponses = {
    /**
     * Response Get Users Users  Get
     *
     * Successful Response
     */
    200: Array<UserRead>;
};

export type GetUsersUsersGetResponse = GetUsersUsersGetResponses[keyof GetUsersUsersGetResponses];

export type ReadClientsClientsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clients/';
};

export type ReadClientsClientsGetResponses = {
    /**
     * Response Read Clients Clients  Get
     *
     * Successful Response
     */
    200: Array<ClientRead>;
};

export type ReadClientsClientsGetResponse = ReadClientsClientsGetResponses[keyof ReadClientsClientsGetResponses];

export type CreateClientClientsPostData = {
    body: ClientCreate;
    path?: never;
    query?: never;
    url: '/clients/';
};

export type CreateClientClientsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateClientClientsPostError = CreateClientClientsPostErrors[keyof CreateClientClientsPostErrors];

export type CreateClientClientsPostResponses = {
    /**
     * Successful Response
     */
    200: ClientRead;
};

export type CreateClientClientsPostResponse = CreateClientClientsPostResponses[keyof CreateClientClientsPostResponses];
