"""Detailed views

Revision ID: 0e263c245743
Revises: bc0d1f4e77fd
Create Date: 2026-01-13 22:51:11.761138

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0e263c245743"
down_revision: Union[str, Sequence[str], None] = "bc0d1f4e77fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
