"""add_dilaps_progress_tracking_fields

Revision ID: 164cf9136460
Revises: 97f535c090a6
Create Date: 2026-03-19 12:55:42.476664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164cf9136460'
down_revision: Union[str, Sequence[str], None] = '97f535c090a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dilaps_runs', sa.Column('total_sections', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('dilaps_runs', sa.Column('current_section', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('dilaps_runs', sa.Column('status_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dilaps_runs', 'status_message')
    op.drop_column('dilaps_runs', 'current_section')
    op.drop_column('dilaps_runs', 'total_sections')
    # ### end Alembic commands ###
