"""fix_remaining_schema_diffs

Revision ID: 233f13d762f7
Revises: e14978fd2d00
Create Date: 2025-12-12 11:03:07.420891

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "233f13d762f7"
down_revision: Union[str, Sequence[str], None] = "e14978fd2d00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Columns 'progress' and 'logs' were already added in b4e5f6g7h8i9
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Do not drop them here if they are managed by another migration
    pass
    # ### end Alembic commands ###
