"""fix_remaining_schema_diffs

Revision ID: 233f13d762f7
Revises: e14978fd2d00
Create Date: 2025-12-12 11:03:07.420891

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "233f13d762f7"
down_revision: Union[str, Sequence[str], None] = "e14978fd2d00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("progress", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "jobs",
        sa.Column(
            "logs",
            postgresql.JSON(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "logs")
    op.drop_column("jobs", "progress")
    # ### end Alembic commands ###
