"""add_is_individual_to_client

Revision ID: 398023069eb4
Revises: 6680129b07d2
Create Date: 2026-01-21 12:59:26.393104

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "398023069eb4"
down_revision: Union[str, Sequence[str], None] = "6680129b07d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("clients")]

    # Add is_individual field with server_default to handle existing rows
    if "is_individual" not in columns:
        op.add_column(
            "clients",
            sa.Column(
                "is_individual",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
            ),
        )
    if "email" not in columns:
        op.add_column("clients", sa.Column("email", sa.String(), nullable=True))
    if "phone" not in columns:
        op.add_column(
            "clients", sa.Column("phone", sa.String(length=64), nullable=True)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "surveys",
        "weather",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "surveys",
        "site_notes",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "surveys",
        "description",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "projects",
        "fee_type",
        existing_type=postgresql.ENUM("fixed", "hourly", "mixed", name="feetype"),
        nullable=False,
    )
    op.drop_column("clients", "phone")
    op.drop_column("clients", "email")
    op.drop_column("clients", "is_individual")
