"""Removed some stuff and added projects

Revision ID: 3c735a18f21d
Revises: 34c29e353e46
Create Date: 2026-01-03 22:45:28.094190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c735a18f21d'
down_revision: Union[str, Sequence[str], None] = '34c29e353e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_types_org_id'), 'project_types', ['org_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('project_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updates', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('forecasted_billable_hours', sa.Integer(), nullable=True),
    sa.Column('contingency_percentage', sa.Integer(), nullable=True),
    sa.Column('forecasted_settlement_amount', sa.Integer(), nullable=True),
    sa.Column('forecasted_fee_amount', sa.Integer(), nullable=True),
    sa.Column('fee_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_job_id'), 'projects', ['job_id'], unique=False)
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.create_index(op.f('ix_projects_project_type_id'), 'projects', ['project_type_id'], unique=False)
    op.add_column('jobs', sa.Column('lead_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_jobs_lead_user_id'), 'jobs', ['lead_user_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'users', ['lead_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_lead_user_id'), table_name='jobs')
    op.drop_column('jobs', 'lead_user_id')
    op.drop_index(op.f('ix_projects_project_type_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_job_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_project_types_org_id'), table_name='project_types')
    op.drop_table('project_types')
    # ### end Alembic commands ###
