"""Add external_id for user back in

Revision ID: 3e2027142b39
Revises: d56dd9c766e4
Create Date: 2025-12-30 23:52:14.902326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2027142b39'
down_revision: Union[str, Sequence[str], None] = 'd56dd9c766e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artefacts', 'preview_file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_artefacts_file_id'), 'artefacts', ['file_id'], unique=False)
    op.create_index(op.f('ix_artefacts_job_id'), 'artefacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_artefacts_preview_file_id'), 'artefacts', ['preview_file_id'], unique=False)
    op.create_index(op.f('ix_artefacts_run_id'), 'artefacts', ['run_id'], unique=False)
    op.add_column('users', sa.Column('external_id', sa.String(), nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint(None, 'users', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'external_id')
    op.drop_index(op.f('ix_artefacts_run_id'), table_name='artefacts')
    op.drop_index(op.f('ix_artefacts_preview_file_id'), table_name='artefacts')
    op.drop_index(op.f('ix_artefacts_job_id'), table_name='artefacts')
    op.drop_index(op.f('ix_artefacts_file_id'), table_name='artefacts')
    op.alter_column('artefacts', 'preview_file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
