"""add_billing_fields

Revision ID: 7166121146ff
Revises: 0e263c245743
Create Date: 2026-01-14 16:53:07.381872

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7166121146ff"
down_revision: Union[str, Sequence[str], None] = "0e263c245743"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_types",
        sa.Column(
            "default_fee_type",
            sa.Enum("FIXED", "HOURLY", "MIXED", name="feetype"),
            nullable=True,
        ),
    )
    op.add_column(
        "project_types",
        sa.Column("default_contingency_percentage", sa.Float(), nullable=True),
    )
    op.add_column("projects", sa.Column("actual_hours", sa.Float(), nullable=True))
    op.add_column(
        "projects", sa.Column("final_settlement_amount", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "final_settlement_amount")
    op.drop_column("projects", "actual_hours")
    op.drop_column("project_types", "default_contingency_percentage")
    op.drop_column("project_types", "default_fee_type")
    # ### end Alembic commands ###
