"""add_billing_fields

Revision ID: 7166121146ff
Revises: 0e263c245743
Create Date: 2026-01-14 16:53:07.381872

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7166121146ff"
down_revision: Union[str, Sequence[str], None] = "0e263c245743"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    project_types_columns = [
        col["name"] for col in inspector.get_columns("project_types")
    ]
    projects_columns = [col["name"] for col in inspector.get_columns("projects")]

    if "default_fee_type" not in project_types_columns:
        op.add_column(
            "project_types",
            sa.Column(
                "default_fee_type",
                sa.Enum("FIXED", "HOURLY", "MIXED", name="feetype"),
                nullable=True,
            ),
        )
    if "default_contingency_percentage" not in project_types_columns:
        op.add_column(
            "project_types",
            sa.Column("default_contingency_percentage", sa.Float(), nullable=True),
        )
    if "actual_hours" not in projects_columns:
        op.add_column("projects", sa.Column("actual_hours", sa.Float(), nullable=True))
    if "final_settlement_amount" not in projects_columns:
        op.add_column(
            "projects", sa.Column("final_settlement_amount", sa.Float(), nullable=True)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "final_settlement_amount")
    op.drop_column("projects", "actual_hours")
    op.drop_column("project_types", "default_contingency_percentage")
    op.drop_column("project_types", "default_fee_type")
    # ### end Alembic commands ###
