"""sessions for auth implementation

Revision ID: 74bf2b102407
Revises: c63778abe4eb
Create Date: 2026-01-02 01:17:20.147618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74bf2b102407'
down_revision: Union[str, Sequence[str], None] = 'c63778abe4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent tables first
    op.drop_index(op.f('ix_run_files_run_role'), table_name='run_files')
    op.drop_table('run_files')
    
    op.drop_index(op.f('ix_artefacts_file_id'), table_name='artefacts')
    op.drop_index(op.f('ix_artefacts_job_created_at'), table_name='artefacts')
    op.drop_index(op.f('ix_artefacts_job_id'), table_name='artefacts')
    op.drop_index(op.f('ix_artefacts_org_id'), table_name='artefacts')
    op.drop_index(op.f('ix_artefacts_preview_file_id'), table_name='artefacts')
    op.drop_index(op.f('ix_artefacts_run_id'), table_name='artefacts')
    op.drop_index(op.f('ix_artefacts_run_version_desc'), table_name='artefacts')
    op.drop_table('artefacts')

    op.drop_index(op.f('ix_job_files_added_by_user_id'), table_name='job_files')
    op.drop_table('job_files')

    op.drop_index(op.f('ix_runs_created_by_user_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_job_created_at'), table_name='runs')
    op.drop_index(op.f('ix_runs_job_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_org_created_at'), table_name='runs')
    op.drop_index(op.f('ix_runs_org_id'), table_name='runs')
    op.drop_table('runs')

    op.drop_index(op.f('ix_jobs_client_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_by_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_org_client'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_org_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_org_id'), table_name='jobs')
    op.drop_table('jobs')

    op.drop_index(op.f('ix_files_org_created_at'), table_name='files')
    op.drop_index(op.f('ix_files_org_id'), table_name='files')
    op.drop_index(op.f('ix_files_org_role_created_at'), table_name='files')
    op.drop_index(op.f('ix_files_org_sha256'), table_name='files')
    op.drop_index(op.f('ix_files_owner_user_id'), table_name='files')
    op.drop_table('files')

    op.drop_index(op.f('ix_client_contacts_client_id'), table_name='client_contacts')
    op.drop_table('client_contacts')

    op.drop_index(op.f('ix_clients_org_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_org_name'), table_name='clients')
    op.drop_table('clients')

    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_table('users')

    op.drop_table('orgs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('role_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('client_contacts_client_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('client_contacts_pkey'))
    )
    op.create_index(op.f('ix_client_contacts_client_id'), 'client_contacts', ['client_id'], unique=False)
    op.create_table('run_files',
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('template', 'preview_pdf', 'artefact', 'input', name='file_role'), server_default=sa.text("'input'::file_role"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('run_files_file_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('run_files_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'file_id', name=op.f('pk_run_files'))
    )
    op.create_index(op.f('ix_run_files_run_role'), 'run_files', ['run_id', 'role'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('clients_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name='clients_org_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='clients_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_clients_org_name'), 'clients', ['org_id', 'name'], unique=False)
    op.create_index(op.f('ix_clients_org_id'), 'clients', ['org_id'], unique=False)
    op.create_table('artefacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artefact_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preview_file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_artefacts_version_positive')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('artefacts_file_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('artefacts_job_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('artefacts_org_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preview_file_id'], ['files.id'], name=op.f('artefacts_preview_file_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('artefacts_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('artefacts_pkey')),
    sa.UniqueConstraint('run_id', 'version', name=op.f('uq_artefacts_run_version'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_artefacts_run_version_desc'), 'artefacts', ['run_id', 'version'], unique=False)
    op.create_index(op.f('ix_artefacts_run_id'), 'artefacts', ['run_id'], unique=False)
    op.create_index(op.f('ix_artefacts_preview_file_id'), 'artefacts', ['preview_file_id'], unique=False)
    op.create_index(op.f('ix_artefacts_org_id'), 'artefacts', ['org_id'], unique=False)
    op.create_index(op.f('ix_artefacts_job_id'), 'artefacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_artefacts_job_created_at'), 'artefacts', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_artefacts_file_id'), 'artefacts', ['file_id'], unique=False)
    op.create_table('orgs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('orgs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='orgs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('idle', 'presigning', 'uploading', 'generating', 'completed', 'error', name='run_status'), server_default=sa.text("'idle'::run_status"), autoincrement=False, nullable=False),
    sa.Column('upload_progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('model_responses', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('runs_created_by_user_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('runs_job_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('runs_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('runs_pkey'))
    )
    op.create_index(op.f('ix_runs_org_id'), 'runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_runs_org_created_at'), 'runs', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_runs_job_id'), 'runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_runs_job_created_at'), 'runs', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_runs_created_by_user_id'), 'runs', ['created_by_user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('jobs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='jobs_client_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='jobs_created_by_user_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name='jobs_org_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='jobs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_jobs_org_id'), 'jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_jobs_org_created_at'), 'jobs', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_org_client'), 'jobs', ['org_id', 'client_id'], unique=False)
    op.create_index(op.f('ix_jobs_created_by_user_id'), 'jobs', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_jobs_client_id'), 'jobs', ['client_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('files_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('template', 'preview_pdf', 'artefact', 'input', name='file_role'), server_default=sa.text("'input'::file_role"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name='files_org_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='files_owner_user_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='files_pkey'),
    sa.UniqueConstraint('storage_key', name='uq_files_storage_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_files_owner_user_id'), 'files', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_files_org_sha256'), 'files', ['org_id', 'sha256'], unique=False)
    op.create_index(op.f('ix_files_org_role_created_at'), 'files', ['org_id', 'role', 'created_at'], unique=False)
    op.create_index(op.f('ix_files_org_id'), 'files', ['org_id'], unique=False)
    op.create_index(op.f('ix_files_org_created_at'), 'files', ['org_id', 'created_at'], unique=False)
    op.create_table('job_files',
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], name=op.f('job_files_added_by_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('job_files_file_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('job_files_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'file_id', name=op.f('pk_job_files'))
    )
    op.create_index(op.f('ix_job_files_added_by_user_id'), 'job_files', ['added_by_user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('member', 'admin', name='user_role'), server_default=sa.text("'member'::user_role"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('users_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('external_id', name=op.f('users_external_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
