"""added preview pdf collumn to job

Revision ID: 9112e414fb91
Revises: 5e3fb65bcc12
Create Date: 2025-12-28 22:21:34.710475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9112e414fb91"
down_revision: Union[str, Sequence[str], None] = "5e3fb65bcc12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("preview_pdf_document_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "jobs", sa.Column("preview_pdf_document_url", sa.Text(), nullable=True)
    )
    op.alter_column("jobs", "progress", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "jobs",
        "logs",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.create_foreign_key(
        None, "jobs", "documents", ["preview_pdf_document_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "jobs", type_="foreignkey")
    op.alter_column(
        "jobs",
        "logs",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column("jobs", "progress", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("jobs", "preview_pdf_document_url")
    op.drop_column("jobs", "preview_pdf_document_id")
    # ### end Alembic commands ###
