"""fix_artefact_job_relationship

Revision ID: 92f4a8e73016
Revises: f98dd917c9b7
Create Date: 2026-01-03 23:03:01.577353

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '92f4a8e73016'
down_revision: Union[str, Sequence[str], None] = 'f98dd917c9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
