"""remove_billing_add_instruction_type_to_runs_artefacts

Revision ID: 97f535c090a6
Revises: d8f5a9e2b456
Create Date: 2026-01-28 14:54:01.462959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97f535c090a6'
down_revision: Union[str, Sequence[str], None] = 'd8f5a9e2b456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artefacts', sa.Column('instruction_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artefacts', 'project_types', ['instruction_type_id'], ['id'], ondelete='SET NULL')
    op.drop_column('project_types', 'rate')
    op.drop_column('project_types', 'default_contingency_percentage')
    op.drop_column('project_types', 'default_fee_type')
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('projects', 'name')
    op.drop_column('projects', 'final_settlement_amount')
    op.drop_column('projects', 'actual_hours')
    op.drop_column('projects', 'contingency_percentage')
    op.drop_column('projects', 'forecasted_billable_hours')
    op.drop_column('projects', 'forecasted_settlement_amount')
    op.drop_column('projects', 'forecasted_fee_amount')
    op.drop_column('projects', 'rate')
    op.drop_column('projects', 'fee_type')
    op.add_column('runs', sa.Column('instruction_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'runs', 'project_types', ['instruction_type_id'], ['id'], ondelete='SET NULL')
    op.alter_column('surveys', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('surveys', 'site_notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('surveys', 'weather',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'weather',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('surveys', 'site_notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('surveys', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_column('runs', 'instruction_type_id')
    op.add_column('projects', sa.Column('fee_type', postgresql.ENUM('fixed', 'hourly', 'mixed', name='feetype'), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('forecasted_fee_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('forecasted_settlement_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('forecasted_billable_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('contingency_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('actual_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('final_settlement_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('project_types', sa.Column('default_fee_type', postgresql.ENUM('fixed', 'hourly', 'mixed', name='feetype'), autoincrement=False, nullable=True))
    op.add_column('project_types', sa.Column('default_contingency_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('project_types', sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artefacts', type_='foreignkey')
    op.drop_column('artefacts', 'instruction_type_id')
    # ### end Alembic commands ###
