"""add_leads_quotes_surveys_tasks

Revision ID: a85f20d84b15
Revises: 5115db899230
Create Date: 2026-01-15 00:28:53.094604

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = "a85f20d84b15"
down_revision: Union[str, Sequence[str], None] = "5115db899230"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Some tables may already exist from previous dev work, using if_not_exists
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    # Create new tables if they don't exist
    # Leads table
    if "leads" not in existing_tables:
        op.create_table(
            "leads",
            sa.Column(
                "name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
            ),
            sa.Column(
                "contact_name",
                sqlmodel.sql.sqltypes.AutoString(length=255),
                nullable=True,
            ),
            sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column(
                "phone", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
            ),
            sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.Column("updates", sa.JSON(), nullable=True),
            sa.Column("org_id", sa.Integer(), nullable=False),
            sa.Column("converted_client_id", sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(
                ["converted_client_id"], ["clients.id"], ondelete="SET NULL"
            ),
            sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )

    # Quotes table
    if "quotes" not in existing_tables:
        op.create_table(
            "quotes",
            sa.Column(
                "name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
            ),
            sa.Column("estimated_fee", sa.Float(), nullable=True),
            sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("expected_start_date", sa.Date(), nullable=True),
            sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.Column("updates", sa.JSON(), nullable=True),
            sa.Column("org_id", sa.Integer(), nullable=False),
            sa.Column("client_id", sa.Integer(), nullable=True),
            sa.Column("lead_id", sa.Integer(), nullable=True),
            sa.Column("converted_job_id", sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="SET NULL"),
            sa.ForeignKeyConstraint(
                ["converted_job_id"], ["jobs.id"], ondelete="SET NULL"
            ),
            sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], ondelete="SET NULL"),
            sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )

    # Quote Lines table
    if "quote_lines" not in existing_tables:
        op.create_table(
            "quote_lines",
            sa.Column("estimated_fee", sa.Float(), nullable=True),
            sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("quote_id", sa.Integer(), nullable=False),
            sa.Column("project_type_id", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                ["project_type_id"], ["project_types.id"], ondelete="RESTRICT"
            ),
            sa.ForeignKeyConstraint(["quote_id"], ["quotes.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )

    # Surveys table
    if "surveys" not in existing_tables:
        op.create_table(
            "surveys",
            sa.Column("date", sa.Date(), nullable=False),
            sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.Column("org_id", sa.Integer(), nullable=False),
            sa.Column("job_id", sa.Integer(), nullable=False),
            sa.Column("surveyor_id", sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["surveyor_id"], ["users.id"], ondelete="SET NULL"),
            sa.PrimaryKeyConstraint("id"),
        )

    # Tasks table
    if "tasks" not in existing_tables:
        op.create_table(
            "tasks",
            sa.Column(
                "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
            ),
            sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("order", sa.Integer(), nullable=False),
            sa.Column("estimated_hours", sa.Float(), nullable=True),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.Column("org_id", sa.Integer(), nullable=False),
            sa.Column("project_id", sa.Integer(), nullable=False),
            sa.Column("assignee_id", sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(["assignee_id"], ["users.id"], ondelete="SET NULL"),
            sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(
                ["project_id"], ["projects.id"], ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("id"),
        )

    # Add columns to existing tables (with checks for existing columns)
    files_columns = [c["name"] for c in inspector.get_columns("files")]
    if "survey_id" not in files_columns:
        op.add_column("files", sa.Column("survey_id", sa.Integer(), nullable=True))
        op.create_foreign_key(
            None, "files", "surveys", ["survey_id"], ["id"], ondelete="SET NULL"
        )

    jobs_columns = [c["name"] for c in inspector.get_columns("jobs")]
    if "updates" not in jobs_columns:
        op.add_column("jobs", sa.Column("updates", sa.JSON(), nullable=True))

    projects_columns = [c["name"] for c in inspector.get_columns("projects")]
    if "notes" not in projects_columns:
        op.add_column(
            "projects",
            sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        )
    if "deadline" not in projects_columns:
        op.add_column("projects", sa.Column("deadline", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "deadline")
    op.drop_column("projects", "notes")
    op.drop_column("jobs", "updates")
    op.drop_constraint(None, "files", type_="foreignkey")
    op.drop_column("files", "survey_id")
    op.drop_table("tasks")
    op.drop_table("surveys")
    op.drop_table("quote_lines")
    op.drop_table("quotes")
    op.drop_table("leads")
    # ### end Alembic commands ###
