"""fix_run_files_relationship

Revision ID: bacf1ca89e32
Revises: 92f4a8e73016
Create Date: 2026-01-03 23:07:29.330190

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'bacf1ca89e32'
down_revision: Union[str, Sequence[str], None] = '92f4a8e73016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
