"""Fix enum defs

Revision ID: d766583593a6
Revises: 3e2027142b39
Create Date: 2025-12-31 00:09:52.284421

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'd766583593a6'
down_revision: Union[str, Sequence[str], None] = '3e2027142b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
