"""fix_remaining_schema_diffs

Revision ID: e14978fd2d00
Revises: b4e5f6g7h8i9
Create Date: 2025-12-12 10:49:33.047562

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e14978fd2d00"
down_revision: Union[str, Sequence[str], None] = "b4e5f6g7h8i9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Columns already exist in DB, skipping add_column
    # op.add_column('jobs', sa.Column('progress', sa.Integer(), server_default='0', nullable=False))
    # op.add_column('jobs', sa.Column('logs', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False))
    # Constraint already exists
    # op.create_unique_constraint('uix_org_template', 'organisation_templates', ['org_id', 'template_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uix_org_template', 'organisation_templates', type_='unique')
    # op.drop_column('jobs', 'logs')
    # op.drop_column('jobs', 'progress')
    # ### end Alembic commands ###
