"""make org_id nullable in job an document

Revision ID: eb2a83abe56b
Revises: 39f338e867c8
Create Date: 2025-12-09 22:34:44.295083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2a83abe56b'
down_revision: Union[str, Sequence[str], None] = '39f338e867c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
