"""add_projects_relationship_to_org

Revision ID: f98dd917c9b7
Revises: 3c735a18f21d
Create Date: 2026-01-03 22:56:09.891806

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'f98dd917c9b7'
down_revision: Union[str, Sequence[str], None] = '3c735a18f21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
